# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from __future__ import annotations

from datetime import datetime
from typing import List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: Optional[str] = Field("", title="Workflow Description")


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class SpatialGrouper(BaseModel):
    spatial_index_name: str = Field(..., title="Spatial Regions")


class TemporalGrouper(BaseModel):
    temporal_index: str = Field(..., title="Time")


class ValueGrouper(BaseModel):
    index_name: str = Field(..., title="Category")


class Grouper(RootModel[ValueGrouper]):
    root: ValueGrouper


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: Optional[TimezoneInfo] = Field(None, title="Timezone")
    time_format: Optional[str] = Field(
        "%d %b %Y %H:%M:%S", description="The time format", title="Time Format"
    )


class Groupers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    groupers: Optional[List[Union[ValueGrouper, TemporalGrouper, SpatialGrouper]]] = (
        Field(
            None,
            description="            Specify how the data should be grouped to create the views for your dashboard.\n            This field is optional; if left blank, all the data will appear in a single view.\n            ",
            title=" ",
        )
    )


class FormData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: Optional[WorkflowDetails] = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Set Workflow Details",
    )
    time_range: Optional[TimeRange] = Field(
        None,
        description="Choose the period of time to analyze.",
        title="Define analysis time range",
    )
    groupers: Optional[Groupers] = Field(None, title="Define temporal groupers")
