# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Bh Antipoaching
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import groupbykey as groupbykey
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_ext_bahari_hai.tasks import (
    assemble_dashboard_widgets as assemble_dashboard_widgets,
)
from ecoscope_workflows_ext_bahari_hai.tasks import clean_dataframe as clean_dataframe
from ecoscope_workflows_ext_bahari_hai.tasks import draw_arrests_map as draw_arrests_map
from ecoscope_workflows_ext_bahari_hai.tasks import draw_donut_chart as draw_donut_chart
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_ecograph_map as draw_ecograph_map,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_illegal_events_map as draw_illegal_events_map,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_illegal_fishing_map as draw_illegal_fishing_map,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_mangrove_logging_map as draw_mangrove_logging_map,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_poached_turtles_map as draw_poached_turtles_map,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_poaching_map as draw_poaching_map,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_proportional_bar_chart as draw_proportional_bar_chart,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_stacked_bar_chart as draw_stacked_bar_chart,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_standardized_rate_map as draw_standardized_rate_map,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_summary_dashboard as draw_summary_dashboard,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_weighted_effort_map as draw_weighted_effort_map,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    get_generation_date as get_generation_date,
)
from ecoscope_workflows_ext_bahari_hai.tasks import get_report_year as get_report_year
from ecoscope_workflows_ext_bahari_hai.tasks import (
    prepare_category_counts as prepare_category_counts,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    prepare_grouped_summary as prepare_grouped_summary,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    prepare_pivot_summary as prepare_pivot_summary,
)
from ecoscope_workflows_ext_bahari_hai.tasks import render_report as render_report
from ecoscope_workflows_ext_bahari_hai.tasks import (
    summarize_by_village as summarize_by_village,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    summarize_patrols as summarize_patrols,
)
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_custom.tasks.io import load_df as load_df
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_bar_chart as draw_bar_chart,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_line_chart as draw_line_chart,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_table as draw_table
from ecoscope_workflows_ext_ste.tasks import (
    fetch_and_persist_file as fetch_and_persist_file,
)

# %% [markdown]
# ## Set Workflow Details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Define analysis time range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
    time_format=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .partial(**time_range_params)
    .call()
)


# %% [markdown]
# ## CSV input

# %%
# parameters

csv_input_params = dict()

# %%
# call the task


csv_input = (
    fetch_and_persist_file.set_task_instance_id("csv_input")
    .handle_errors()
    .with_tracing()
    .partial(
        url="https://raw.githubusercontent.com/wildlife-dynamics/wt-bh-village-games/ae1f5bfb247c0bdde169caaaaf4e5c96cafb6b75/data/patrol_findings_with_village.csv",
        output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        unzip=False,
        retries=3,
        overwrite_existing=False,
        **csv_input_params,
    )
    .call()
)


# %% [markdown]
# ## Load bh data from CSV

# %%
# parameters

load_data_params = dict()

# %%
# call the task


load_data = (
    load_df.set_task_instance_id("load_data")
    .handle_errors()
    .with_tracing()
    .partial(
        file_path=csv_input,
        layer="landDx_polygons",
        deserialize_json=False,
        **load_data_params,
    )
    .call()
)


# %% [markdown]
# ## Marine layers path

# %%
# parameters

marine_layers_input_params = dict()

# %%
# call the task


marine_layers_input = (
    fetch_and_persist_file.set_task_instance_id("marine_layers_input")
    .handle_errors()
    .with_tracing()
    .partial(
        url="https://drive.google.com/uc?export=download&id=1pNu0xS9lMN-O4SPpSiBihYcUTOGwN5_H",
        output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        unzip=True,
        retries=3,
        overwrite_existing=False,
        **marine_layers_input_params,
    )
    .call()
)


# %% [markdown]
# ## Report template path

# %%
# parameters

report_template_input_params = dict()

# %%
# call the task


report_template_input = (
    fetch_and_persist_file.set_task_instance_id("report_template_input")
    .handle_errors()
    .with_tracing()
    .partial(
        url="https://docs.google.com/document/d/1qqy2OdAL_RJirep78TlCOBxHL4e6W--5/export?format=docx",
        output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        unzip=False,
        retries=3,
        overwrite_existing=False,
        **report_template_input_params,
    )
    .call()
)


# %% [markdown]
# ## Clean and prepare patrol data

# %%
# parameters

clean_data_params = dict()

# %%
# call the task


clean_data = (
    clean_dataframe.set_task_instance_id("clean_data")
    .handle_errors()
    .with_tracing()
    .partial(
        data=load_data,
        date_columns=["Patrol Start Date", "Waypoint Date"],
        date_format="%d-%b-%y",
        groupby_period=["Year", "Month", "Quarter"],
        numeric_columns=["X", "Y"],
        drop_duplicates=False,
        **clean_data_params,
    )
    .call()
)


# %% [markdown]
# ## Define temporal groupers

# %%
# parameters

groupers_params = dict(
    groupers=...,
)

# %%
# call the task


groupers = (
    set_groupers.set_task_instance_id("groupers")
    .handle_errors()
    .with_tracing()
    .partial(**groupers_params)
    .call()
)


# %% [markdown]
# ## Split data into temporal groups

# %%
# parameters

split_data_params = dict()

# %%
# call the task


split_data = (
    split_groups.set_task_instance_id("split_data")
    .handle_errors()
    .with_tracing()
    .partial(df=clean_data, groupers=groupers, **split_data_params)
    .call()
)


# %% [markdown]
# ## Summarize patrols by year

# %%
# parameters

patrol_summaries_by_year_params = dict()

# %%
# call the task


patrol_summaries_by_year = (
    summarize_patrols.set_task_instance_id("patrol_summaries_by_year")
    .handle_errors()
    .with_tracing()
    .partial(df=clean_data, **patrol_summaries_by_year_params)
    .call()
)


# %% [markdown]
# ## Create multi-year patrol summary table

# %%
# parameters

patrol_summary_table_params = dict()

# %%
# call the task


patrol_summary_table = (
    draw_table.set_task_instance_id("patrol_summary_table")
    .handle_errors()
    .with_tracing()
    .partial(
        dataframe=patrol_summaries_by_year,
        columns=["Year", "patrols", "hours", "incidents"],
        widget_id="Patrol summaries",
        table_config={
            "enable_sorting": True,
            "enable_filtering": False,
            "enable_download": False,
            "hide_header": False,
        },
        **patrol_summary_table_params,
    )
    .call()
)


# %% [markdown]
# ## Persist patrol summary table HTML

# %%
# parameters

persist_patrol_summary_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_patrol_summary_html = (
    persist_text.set_task_instance_id("persist_patrol_summary_html")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="patrol_summary",
        text=patrol_summary_table,
        **persist_patrol_summary_html_params,
    )
    .call()
)


# %% [markdown]
# ## Convert patrol summary table HTML to PNG

# %%
# parameters

html_to_png_patrol_summary_params = dict()

# %%
# call the task


html_to_png_patrol_summary = (
    html_to_png.set_task_instance_id("html_to_png_patrol_summary")
    .handle_errors()
    .with_tracing()
    .partial(
        html_path=persist_patrol_summary_html,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **html_to_png_patrol_summary_params,
    )
    .call()
)


# %% [markdown]
# ## Create patrol summary widget

# %%
# parameters

patrol_summary_widget_params = dict(
    view=...,
)

# %%
# call the task


patrol_summary_widget = (
    create_table_widget_single_view.set_task_instance_id("patrol_summary_widget")
    .handle_errors()
    .with_tracing()
    .partial(
        title="Patrol summaries",
        data=persist_patrol_summary_html,
        **patrol_summary_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Draw patrols per year chart

# %%
# parameters

patrols_line_chart_params = dict()

# %%
# call the task


patrols_line_chart = (
    draw_line_chart.set_task_instance_id("patrols_line_chart")
    .handle_errors()
    .with_tracing()
    .partial(
        dataframe=patrol_summaries_by_year,
        x_column="Year",
        y_column="patrols",
        category_column=None,
        widget_id="Patrols per Year",
        smoothing=None,
        layout_kwargs={
            "title": "Number of Patrols per Year",
            "title_x": 0.5,
            "font_size": 12.0,
            "font_color": "black",
            "font_family": "Arial",
            "yaxis": {
                "title": "Number of Patrols",
                "tick_font_size": 8,
                "title_font_size": 10,
            },
            "xaxis": {
                "title": "Year",
                "tick_font_size": 8,
                "title_font_size": 10,
                "tickmode": "linear",
                "dtick": 1,
            },
            "margin": {"t": 120, "b": 80, "l": 80, "r": 40},
        },
        line_kwargs={
            "color": "#2c3e50",
            "width": 3,
            "shape": "linear",
            "show_markers": True,
        },
        **patrols_line_chart_params,
    )
    .call()
)


# %% [markdown]
# ## Persist patrols chart HTML

# %%
# parameters

persist_patrols_chart_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_patrols_chart_html = (
    persist_text.set_task_instance_id("persist_patrols_chart_html")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="patrols_per_year",
        text=patrols_line_chart,
        **persist_patrols_chart_html_params,
    )
    .call()
)


# %% [markdown]
# ## Convert patrols chart HTML to PNG

# %%
# parameters

html_to_png_patrols_chart_params = dict()

# %%
# call the task


html_to_png_patrols_chart = (
    html_to_png.set_task_instance_id("html_to_png_patrols_chart")
    .handle_errors()
    .with_tracing()
    .partial(
        html_path=persist_patrols_chart_html,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **html_to_png_patrols_chart_params,
    )
    .call()
)


# %% [markdown]
# ## Create patrols chart widget

# %%
# parameters

patrols_chart_widget_params = dict(
    view=...,
)

# %%
# call the task


patrols_chart_widget = (
    create_plot_widget_single_view.set_task_instance_id("patrols_chart_widget")
    .handle_errors()
    .with_tracing()
    .partial(
        title="Patrols per Year",
        data=persist_patrols_chart_html,
        **patrols_chart_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Draw patrol hours per year chart

# %%
# parameters

hours_line_chart_params = dict()

# %%
# call the task


hours_line_chart = (
    draw_line_chart.set_task_instance_id("hours_line_chart")
    .handle_errors()
    .with_tracing()
    .partial(
        dataframe=patrol_summaries_by_year,
        x_column="Year",
        y_column="hours",
        category_column=None,
        widget_id="Patrol Hours per Year",
        smoothing=None,
        layout_kwargs={
            "title": "Patrol Hours per Year",
            "title_x": 0.5,
            "font_size": 12.0,
            "font_color": "black",
            "font_family": "Arial",
            "yaxis": {
                "title": "Patrol Hours",
                "tick_font_size": 8,
                "title_font_size": 10,
            },
            "xaxis": {
                "title": "Year",
                "tick_font_size": 8,
                "title_font_size": 10,
                "tickmode": "linear",
                "dtick": 1,
            },
            "margin": {"t": 120, "b": 80, "l": 80, "r": 40},
        },
        line_kwargs={
            "color": "#2c3e50",
            "width": 3,
            "shape": "linear",
            "show_markers": True,
        },
        **hours_line_chart_params,
    )
    .call()
)


# %% [markdown]
# ## Persist hours chart HTML

# %%
# parameters

persist_hours_chart_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_hours_chart_html = (
    persist_text.set_task_instance_id("persist_hours_chart_html")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="patrol_hours_per_year",
        text=hours_line_chart,
        **persist_hours_chart_html_params,
    )
    .call()
)


# %% [markdown]
# ## Convert hours chart HTML to PNG

# %%
# parameters

html_to_png_hours_chart_params = dict()

# %%
# call the task


html_to_png_hours_chart = (
    html_to_png.set_task_instance_id("html_to_png_hours_chart")
    .handle_errors()
    .with_tracing()
    .partial(
        html_path=persist_hours_chart_html,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **html_to_png_hours_chart_params,
    )
    .call()
)


# %% [markdown]
# ## Create hours chart widget

# %%
# parameters

hours_chart_widget_params = dict(
    view=...,
)

# %%
# call the task


hours_chart_widget = (
    create_plot_widget_single_view.set_task_instance_id("hours_chart_widget")
    .handle_errors()
    .with_tracing()
    .partial(
        title="Patrol Hours per Year",
        data=persist_hours_chart_html,
        **hours_chart_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Draw incidents per year chart

# %%
# parameters

incidents_line_chart_params = dict()

# %%
# call the task


incidents_line_chart = (
    draw_line_chart.set_task_instance_id("incidents_line_chart")
    .handle_errors()
    .with_tracing()
    .partial(
        dataframe=patrol_summaries_by_year,
        x_column="Year",
        y_column="incidents",
        category_column=None,
        widget_id="Incidents per Year",
        smoothing=None,
        layout_kwargs={
            "title": "Number of Incidents per Year",
            "title_x": 0.5,
            "font_size": 12,
            "font_color": "black",
            "font_family": "Arial",
            "yaxis": {
                "title": "Number of Incidents",
                "tick_font_size": 8,
                "title_font_size": 10,
            },
            "xaxis": {
                "title": "Year",
                "tick_font_size": 8,
                "title_font_size": 10,
                "tickmode": "linear",
                "dtick": 1,
            },
            "margin": {"t": 120, "b": 80, "l": 80, "r": 40},
        },
        line_kwargs={
            "color": "#2c3e50",
            "width": 3,
            "shape": "linear",
            "show_markers": True,
            "smoothing": False,
        },
        **incidents_line_chart_params,
    )
    .call()
)


# %% [markdown]
# ## Persist incidents chart HTML

# %%
# parameters

persist_incidents_chart_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_incidents_chart_html = (
    persist_text.set_task_instance_id("persist_incidents_chart_html")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="incidents_per_year",
        text=incidents_line_chart,
        **persist_incidents_chart_html_params,
    )
    .call()
)


# %% [markdown]
# ## Convert incidents chart HTML to PNG

# %%
# parameters

html_to_png_incidents_chart_params = dict()

# %%
# call the task


html_to_png_incidents_chart = (
    html_to_png.set_task_instance_id("html_to_png_incidents_chart")
    .handle_errors()
    .with_tracing()
    .partial(
        html_path=persist_incidents_chart_html,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **html_to_png_incidents_chart_params,
    )
    .call()
)


# %% [markdown]
# ## Create incidents chart widget

# %%
# parameters

incidents_chart_widget_params = dict(
    view=...,
)

# %%
# call the task


incidents_chart_widget = (
    create_plot_widget_single_view.set_task_instance_id("incidents_chart_widget")
    .handle_errors()
    .with_tracing()
    .partial(
        title="Incidents per Year",
        data=persist_incidents_chart_html,
        **incidents_chart_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Summarize patrols by village

# %%
# parameters

village_summaries_params = dict()

# %%
# call the task


village_summaries = (
    summarize_by_village.set_task_instance_id("village_summaries")
    .handle_errors()
    .with_tracing()
    .partial(df=clean_data, groupers=groupers, **village_summaries_params)
    .call()
)


# %% [markdown]
# ## Create village summary table

# %%
# parameters

village_summary_table_params = dict()

# %%
# call the task


village_summary_table = (
    draw_table.set_task_instance_id("village_summary_table")
    .handle_errors()
    .with_tracing()
    .partial(
        dataframe=village_summaries,
        columns=[
            "Village",
            "Number Of Patrols",
            "Total Patrol Hours",
            "Mangrove Logging",
            "Poaching",
            "Illegal Fishing",
            "Damaging Coral",
            "Arrests",
        ],
        widget_id="Village Patrol Summary",
        table_config={
            "enable_sorting": True,
            "enable_filtering": False,
            "enable_download": False,
            "hide_header": False,
        },
        **village_summary_table_params,
    )
    .call()
)


# %% [markdown]
# ## Persist village summary table HTML

# %%
# parameters

persist_village_summary_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_village_summary_html = (
    persist_text.set_task_instance_id("persist_village_summary_html")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="village_summary",
        text=village_summary_table,
        **persist_village_summary_html_params,
    )
    .call()
)


# %% [markdown]
# ## Convert village summary table HTML to PNG

# %%
# parameters

html_to_png_village_summary_params = dict()

# %%
# call the task


html_to_png_village_summary = (
    html_to_png.set_task_instance_id("html_to_png_village_summary")
    .handle_errors()
    .with_tracing()
    .partial(
        html_path=persist_village_summary_html,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **html_to_png_village_summary_params,
    )
    .call()
)


# %% [markdown]
# ## Create village summary widget

# %%
# parameters

village_summary_widget_params = dict(
    view=...,
)

# %%
# call the task


village_summary_widget = (
    create_table_widget_single_view.set_task_instance_id("village_summary_widget")
    .handle_errors()
    .with_tracing()
    .partial(
        title="Village Patrol Summary",
        data=persist_village_summary_html,
        **village_summary_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Prepare patrol effort data

# %%
# parameters

patrol_effort_data_params = dict()

# %%
# call the task


patrol_effort_data = (
    prepare_pivot_summary.set_task_instance_id("patrol_effort_data")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        groupers=groupers,
        pivot_column="Patrol Transport Type",
        value_column="Patrol ID",
        aggregation="nunique",
        multiplier=8.0,
        pivot_values=["Boat", "Foot", "Vehicle"],
        station_column="Station",
        station_filter="Sector",
        **patrol_effort_data_params,
    )
    .call()
)


# %% [markdown]
# ## Draw patrol effort bar chart

# %%
# parameters

patrol_effort_chart_params = dict()

# %%
# call the task


patrol_effort_chart = (
    draw_bar_chart.set_task_instance_id("patrol_effort_chart")
    .handle_errors()
    .with_tracing()
    .partial(
        dataframe=patrol_effort_data,
        category="Year",
        bar_chart_configs=[
            {"column": "Boat", "agg_func": "sum", "label": "Boat"},
            {"column": "Foot", "agg_func": "sum", "label": "Foot"},
            {"column": "Vehicle", "agg_func": "sum", "label": "Vehicle"},
        ],
        layout_kwargs={
            "title": "Patrol Effort by Transport Type",
            "title_x": 0.5,
            "font_size": 12,
            "font_color": "black",
            "font_family": "Arial",
            "yaxis": {
                "title": "Patrol Hours",
                "tick_font_size": 8,
                "title_font_size": 10,
            },
            "xaxis": {"title": "Period", "tick_font_size": 8, "title_font_size": 10},
        },
        widget_id="Patrol Effort by Transport Type",
        **patrol_effort_chart_params,
    )
    .call()
)


# %% [markdown]
# ## Persist patrol effort chart HTML

# %%
# parameters

persist_patrol_effort_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_patrol_effort_html = (
    persist_text.set_task_instance_id("persist_patrol_effort_html")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="patrol_effort",
        text=patrol_effort_chart,
        **persist_patrol_effort_html_params,
    )
    .call()
)


# %% [markdown]
# ## Convert patrol effort chart HTML to PNG

# %%
# parameters

html_to_png_patrol_effort_chart_params = dict()

# %%
# call the task


html_to_png_patrol_effort_chart = (
    html_to_png.set_task_instance_id("html_to_png_patrol_effort_chart")
    .handle_errors()
    .with_tracing()
    .partial(
        html_path=persist_patrol_effort_html,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **html_to_png_patrol_effort_chart_params,
    )
    .call()
)


# %% [markdown]
# ## Create patrol effort widget

# %%
# parameters

patrol_effort_widget_params = dict(
    view=...,
)

# %%
# call the task


patrol_effort_widget = (
    create_plot_widget_single_view.set_task_instance_id("patrol_effort_widget")
    .handle_errors()
    .with_tracing()
    .partial(
        title="Patrol Effort by Transport Type",
        data=persist_patrol_effort_html,
        **patrol_effort_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Prepare patrol transport summary data

# %%
# parameters

patrol_transport_data_params = dict()

# %%
# call the task


patrol_transport_data = (
    prepare_grouped_summary.set_task_instance_id("patrol_transport_data")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        groupers=groupers,
        group_column="Patrol Transport Type",
        aggregations={"Patrol Count": "Patrol ID:nunique"},
        derived_columns={"Patrol Hours": "Patrol Count * 8.0"},
        group_values=["Boat", "Foot", "Vehicle"],
        station_column="Station",
        station_filter="Sector",
        most_recent_period_only=False,
        **patrol_transport_data_params,
    )
    .call()
)


# %% [markdown]
# ## Draw patrol count by transport type chart

# %%
# parameters

patrol_transport_count_chart_params = dict()

# %%
# call the task


patrol_transport_count_chart = (
    draw_bar_chart.set_task_instance_id("patrol_transport_count_chart")
    .handle_errors()
    .with_tracing()
    .partial(
        dataframe=patrol_transport_data,
        category="Patrol Transport Type",
        bar_chart_configs=[
            {
                "column": "Patrol Count",
                "agg_func": "sum",
                "label": "Count",
                "text": "Patrol Count",
                "textposition": "outside",
                "textfont_size": 12,
            }
        ],
        layout_kwargs={
            "title": "Number of Patrols by Transport Type",
            "title_x": 0.5,
            "font_size": 12,
            "font_color": "black",
            "font_family": "Arial",
            "yaxis": {
                "title": "Number of Patrols",
                "title_font_size": 10,
                "tick_font_size": 8,
            },
            "xaxis": {
                "title": "Transport Type",
                "title_font_size": 10,
                "tick_font_size": 8,
            },
            "margin": {"t": 140, "b": 120, "l": 100, "r": 100},
        },
        widget_id="Patrol Count by Transport Type",
        **patrol_transport_count_chart_params,
    )
    .call()
)


# %% [markdown]
# ## Persist patrol count transport chart HTML

# %%
# parameters

persist_transport_count_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_transport_count_html = (
    persist_text.set_task_instance_id("persist_transport_count_html")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="transport_patrol_count",
        text=patrol_transport_count_chart,
        **persist_transport_count_html_params,
    )
    .call()
)


# %% [markdown]
# ## Convert patrol count transport chart HTML to PNG

# %%
# parameters

png_transport_count_chart_params = dict()

# %%
# call the task


png_transport_count_chart = (
    html_to_png.set_task_instance_id("png_transport_count_chart")
    .handle_errors()
    .with_tracing()
    .partial(
        html_path=persist_transport_count_html,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_transport_count_chart_params,
    )
    .call()
)


# %% [markdown]
# ## Create patrol count transport widget

# %%
# parameters

patrol_transport_count_widget_params = dict(
    view=...,
)

# %%
# call the task


patrol_transport_count_widget = (
    create_plot_widget_single_view.set_task_instance_id("patrol_transport_count_widget")
    .handle_errors()
    .with_tracing()
    .partial(
        title="Patrol Count by Transport Type",
        data=persist_transport_count_html,
        **patrol_transport_count_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Draw patrol hours by transport type chart

# %%
# parameters

patrol_transport_hours_chart_params = dict()

# %%
# call the task


patrol_transport_hours_chart = (
    draw_bar_chart.set_task_instance_id("patrol_transport_hours_chart")
    .handle_errors()
    .with_tracing()
    .partial(
        dataframe=patrol_transport_data,
        category="Patrol Transport Type",
        bar_chart_configs=[
            {
                "column": "Patrol Hours",
                "agg_func": "sum",
                "label": "Hours",
                "text": "Patrol Hours",
                "textposition": "outside",
                "textfont_size": 12,
            }
        ],
        layout_kwargs={
            "title": "Number of patrol hours by transport type",
            "title_x": 0.5,
            "font_size": 12,
            "font_color": "black",
            "font_family": "Arial",
            "yaxis": {
                "title": "Patrol Hours",
                "title_font_size": 10,
                "tick_font_size": 8,
            },
            "xaxis": {
                "title": "Transport Type",
                "title_font_size": 10,
                "tick_font_size": 8,
            },
            "margin": {"t": 140, "b": 120, "l": 100, "r": 100},
        },
        widget_id="Patrol Hours by Transport Type",
        **patrol_transport_hours_chart_params,
    )
    .call()
)


# %% [markdown]
# ## Persist patrol hours transport chart HTML

# %%
# parameters

persist_transport_hours_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_transport_hours_html = (
    persist_text.set_task_instance_id("persist_transport_hours_html")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="transport_patrol_hours",
        text=patrol_transport_hours_chart,
        **persist_transport_hours_html_params,
    )
    .call()
)


# %% [markdown]
# ## Convert patrol hours transport chart HTML to PNG

# %%
# parameters

png_transport_hours_chart_params = dict()

# %%
# call the task


png_transport_hours_chart = (
    html_to_png.set_task_instance_id("png_transport_hours_chart")
    .handle_errors()
    .with_tracing()
    .partial(
        html_path=persist_transport_hours_html,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_transport_hours_chart_params,
    )
    .call()
)


# %% [markdown]
# ## Create patrol hours transport widget

# %%
# parameters

patrol_transport_hours_widget_params = dict(
    view=...,
)

# %%
# call the task


patrol_transport_hours_widget = (
    create_plot_widget_single_view.set_task_instance_id("patrol_transport_hours_widget")
    .handle_errors()
    .with_tracing()
    .partial(
        title="Patrol Hours by Transport Type",
        data=persist_transport_hours_html,
        **patrol_transport_hours_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Draw illegal activity summary

# %%
# parameters

illegal_activity_summary_params = dict()

# %%
# call the task


illegal_activity_summary = (
    draw_summary_dashboard.set_task_instance_id("illegal_activity_summary")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        groupers=groupers,
        category_column="Observation Category 0",
        categories=[
            "Mangrove Logging",
            "Poaching",
            "Arrests",
            "Damaging Coral",
            "Illegal Fishing",
        ],
        filter_column="Station",
        filter_value="Sector",
        sum_columns={"Poached Turtle Sum": "Sum"},
        chart_title="Illegal Activity Summary",
        n_cols=3,
        widget_id="Illegal Activity Summary",
        **illegal_activity_summary_params,
    )
    .call()
)


# %% [markdown]
# ## Persist illegal activity summary HTML

# %%
# parameters

persist_illegal_activity_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_illegal_activity_html = (
    persist_text.set_task_instance_id("persist_illegal_activity_html")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="illegal_activity_summary",
        text=illegal_activity_summary,
        **persist_illegal_activity_html_params,
    )
    .call()
)


# %% [markdown]
# ## Convert illegal activity summary HTML to PNG

# %%
# parameters

html_to_png_illegal_activity_params = dict()

# %%
# call the task


html_to_png_illegal_activity = (
    html_to_png.set_task_instance_id("html_to_png_illegal_activity")
    .handle_errors()
    .with_tracing()
    .partial(
        html_path=persist_illegal_activity_html,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **html_to_png_illegal_activity_params,
    )
    .call()
)


# %% [markdown]
# ## Create illegal activity summary widget

# %%
# parameters

illegal_activity_widget_params = dict(
    view=...,
)

# %%
# call the task


illegal_activity_widget = (
    create_plot_widget_single_view.set_task_instance_id("illegal_activity_widget")
    .handle_errors()
    .with_tracing()
    .partial(
        title="Illegal Activity Summary",
        data=persist_illegal_activity_html,
        **illegal_activity_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Draw illegal activity donut chart

# %%
# parameters

illegal_activity_donut_params = dict()

# %%
# call the task


illegal_activity_donut = (
    draw_donut_chart.set_task_instance_id("illegal_activity_donut")
    .handle_errors()
    .with_tracing()
    .partial(
        groupers=groupers,
        category_column="Observation Category 0",
        categories=["Mangrove Logging", "Poaching", "Arrests"],
        filter_column="Station",
        filter_value="Sector",
        sum_columns={"Poached Turtle Sum": "Sum"},
        chart_title="Illegal Activities Summary",
        hole=0.4,
        plot_style={
            "marker_colors": [
                "#1f77b4",
                "#2ca02c",
                "#ff7f0e",
                "#d62728",
                "#9467bd",
                "#8c564b",
            ]
        },
        layout_style={
            "showlegend": True,
            "font_size": 8,
            "title_x": 0.5,
            "font_family": "Arial",
            "font_color": "black",
        },
        widget_id="Illegal Activities Donut",
        **illegal_activity_donut_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_data)
)


# %% [markdown]
# ## Persist illegal activity donut HTML

# %%
# parameters

persist_illegal_donut_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_illegal_donut_html = (
    persist_text.set_task_instance_id("persist_illegal_donut_html")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="illegal_activity_donut",
        **persist_illegal_donut_html_params,
    )
    .mapvalues(argnames=["text"], argvalues=illegal_activity_donut)
)


# %% [markdown]
# ## Convert illegal activity donut HTML to PNG

# %%
# parameters

png_illegal_donut_params = dict()

# %%
# call the task


png_illegal_donut = (
    html_to_png.set_task_instance_id("png_illegal_donut")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_illegal_donut_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_illegal_donut_html)
)


# %% [markdown]
# ## Create illegal activity donut widget

# %%
# parameters

illegal_activity_donut_widget_params = dict(
    view=...,
)

# %%
# call the task


illegal_activity_donut_widget = (
    create_plot_widget_single_view.set_task_instance_id("illegal_activity_donut_widget")
    .handle_errors()
    .with_tracing()
    .partial(title="Illegal Activities Donut", **illegal_activity_donut_widget_params)
    .mapvalues(argnames=["data"], argvalues=persist_illegal_donut_html)
)


# %% [markdown]
# ## Prepare mangrove logging evidence data

# %%
# parameters

mangrove_evidence_data_params = dict()

# %%
# call the task


mangrove_evidence_data = (
    prepare_category_counts.set_task_instance_id("mangrove_evidence_data")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        groupers=groupers,
        count_column="Evidence",
        filter_column="Observation Category 0",
        filter_value="mangrove logging",
        station_column="Station",
        station_filter="Sector",
        exclude_values=None,
        **mangrove_evidence_data_params,
    )
    .call()
)


# %% [markdown]
# ## Draw mangrove logging evidence chart

# %%
# parameters

mangrove_evidence_chart_params = dict()

# %%
# call the task


mangrove_evidence_chart = (
    draw_bar_chart.set_task_instance_id("mangrove_evidence_chart")
    .handle_errors()
    .with_tracing()
    .partial(
        dataframe=mangrove_evidence_data,
        category="category",
        bar_chart_configs=[
            {
                "column": "count",
                "agg_func": "sum",
                "label": "Count",
                "text": "count",
                "textposition": "outside",
                "textfont_size": 8,
            }
        ],
        layout_kwargs={
            "title": "Mangrove Logging Evidence",
            "title_x": 0.5,
            "title_y": 0.95,
            "font_size": 12,
            "font_color": "black",
            "margin": {"t": 140, "b": 120},
            "yaxis": {"title": "Count", "title_font_size": 10},
            "xaxis": {"title_font_size": 10, "tickangle": 45},
        },
        widget_id="Mangrove Logging Evidence",
        **mangrove_evidence_chart_params,
    )
    .call()
)


# %% [markdown]
# ## Persist mangrove evidence chart HTML

# %%
# parameters

persist_mangrove_evidence_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_mangrove_evidence_html = (
    persist_text.set_task_instance_id("persist_mangrove_evidence_html")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="mangrove_logging_evidence",
        text=mangrove_evidence_chart,
        **persist_mangrove_evidence_html_params,
    )
    .call()
)


# %% [markdown]
# ## Convert mangrove evidence chart HTML to PNG

# %%
# parameters

png_mangrove_evidence_params = dict()

# %%
# call the task


png_mangrove_evidence = (
    html_to_png.set_task_instance_id("png_mangrove_evidence")
    .handle_errors()
    .with_tracing()
    .partial(
        html_path=persist_mangrove_evidence_html,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": True,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_mangrove_evidence_params,
    )
    .call()
)


# %% [markdown]
# ## Create mangrove evidence widget

# %%
# parameters

mangrove_evidence_widget_params = dict(
    view=...,
)

# %%
# call the task


mangrove_evidence_widget = (
    create_plot_widget_single_view.set_task_instance_id("mangrove_evidence_widget")
    .handle_errors()
    .with_tracing()
    .partial(
        title="Mangrove Logging Evidence",
        data=persist_mangrove_evidence_html,
        **mangrove_evidence_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Prepare poaching evidence data

# %%
# parameters

poaching_evidence_data_params = dict()

# %%
# call the task


poaching_evidence_data = (
    prepare_category_counts.set_task_instance_id("poaching_evidence_data")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        groupers=groupers,
        count_column="Evidence",
        filter_column="Observation Category 0",
        filter_value="poaching",
        station_column="Station",
        station_filter="Sector",
        exclude_values=None,
        **poaching_evidence_data_params,
    )
    .call()
)


# %% [markdown]
# ## Draw poaching evidence chart

# %%
# parameters

poaching_evidence_chart_params = dict()

# %%
# call the task


poaching_evidence_chart = (
    draw_bar_chart.set_task_instance_id("poaching_evidence_chart")
    .handle_errors()
    .with_tracing()
    .partial(
        dataframe=poaching_evidence_data,
        category="category",
        bar_chart_configs=[
            {
                "column": "count",
                "agg_func": "sum",
                "label": "Count",
                "text": "count",
                "textposition": "outside",
                "textfont_size": 10,
            }
        ],
        layout_kwargs={
            "title": "Poaching Evidence",
            "title_x": 0.5,
            "title_y": 0.95,
            "font_size": 12,
            "font_color": "black",
            "margin": {"t": 140, "b": 120},
            "yaxis": {"title": "Count", "title_font_size": 10},
            "xaxis": {"title_font_size": 10, "tickangle": 45},
        },
        widget_id="Poaching Evidence",
        **poaching_evidence_chart_params,
    )
    .call()
)


# %% [markdown]
# ## Persist poaching evidence chart HTML

# %%
# parameters

persist_poaching_evidence_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_poaching_evidence_html = (
    persist_text.set_task_instance_id("persist_poaching_evidence_html")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="poaching_evidence",
        text=poaching_evidence_chart,
        **persist_poaching_evidence_html_params,
    )
    .call()
)


# %% [markdown]
# ## Convert poaching evidence chart HTML to PNG

# %%
# parameters

png_poaching_evidence_params = dict()

# %%
# call the task


png_poaching_evidence = (
    html_to_png.set_task_instance_id("png_poaching_evidence")
    .handle_errors()
    .with_tracing()
    .partial(
        html_path=persist_poaching_evidence_html,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_poaching_evidence_params,
    )
    .call()
)


# %% [markdown]
# ## Create poaching evidence widget

# %%
# parameters

poaching_evidence_widget_params = dict(
    view=...,
)

# %%
# call the task


poaching_evidence_widget = (
    create_plot_widget_single_view.set_task_instance_id("poaching_evidence_widget")
    .handle_errors()
    .with_tracing()
    .partial(
        title="Poaching Evidence",
        data=persist_poaching_evidence_html,
        **poaching_evidence_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Prepare illegal fishing gear data

# %%
# parameters

fishing_gear_data_params = dict()

# %%
# call the task


fishing_gear_data = (
    prepare_category_counts.set_task_instance_id("fishing_gear_data")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        groupers=groupers,
        count_column="Observation",
        filter_column="Resource Use Type",
        filter_value="illegal use",
        exclude_values=["handline", "unknown"],
        station_column="Station",
        station_filter="Sector",
        **fishing_gear_data_params,
    )
    .call()
)


# %% [markdown]
# ## Draw illegal fishing gear chart

# %%
# parameters

fishing_gear_chart_params = dict()

# %%
# call the task


fishing_gear_chart = (
    draw_bar_chart.set_task_instance_id("fishing_gear_chart")
    .handle_errors()
    .with_tracing()
    .partial(
        dataframe=fishing_gear_data,
        category="category",
        bar_chart_configs=[
            {
                "column": "count",
                "agg_func": "sum",
                "label": "Count",
                "text": "count",
                "textposition": "outside",
                "textfont_size": 10,
            }
        ],
        layout_kwargs={
            "title": "Illegal Fishing Gear",
            "title_x": 0.5,
            "title_y": 0.95,
            "font_size": 12,
            "font_color": "black",
            "margin": {"t": 140, "b": 120},
            "yaxis": {"title": "Count", "title_font_size": 10},
            "xaxis": {"title_font_size": 10, "tickangle": 45},
        },
        widget_id="Illegal Fishing Gear",
        **fishing_gear_chart_params,
    )
    .call()
)


# %% [markdown]
# ## Persist fishing gear chart HTML

# %%
# parameters

persist_fishing_gear_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_fishing_gear_html = (
    persist_text.set_task_instance_id("persist_fishing_gear_html")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="illegal_fishing_gear",
        text=fishing_gear_chart,
        **persist_fishing_gear_html_params,
    )
    .call()
)


# %% [markdown]
# ## Convert fishing gear chart HTML to PNG

# %%
# parameters

html_to_png_fishing_gear_chart_params = dict()

# %%
# call the task


html_to_png_fishing_gear_chart = (
    html_to_png.set_task_instance_id("html_to_png_fishing_gear_chart")
    .handle_errors()
    .with_tracing()
    .partial(
        html_path=persist_fishing_gear_html,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **html_to_png_fishing_gear_chart_params,
    )
    .call()
)


# %% [markdown]
# ## Create fishing gear widget

# %%
# parameters

fishing_gear_widget_params = dict(
    view=...,
)

# %%
# call the task


fishing_gear_widget = (
    create_plot_widget_single_view.set_task_instance_id("fishing_gear_widget")
    .handle_errors()
    .with_tracing()
    .partial(
        title="Illegal Fishing Gear",
        data=persist_fishing_gear_html,
        **fishing_gear_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Draw illegal events by sector chart

# %%
# parameters

illegal_events_by_sector_params = dict()

# %%
# call the task


illegal_events_by_sector = (
    draw_stacked_bar_chart.set_task_instance_id("illegal_events_by_sector")
    .handle_errors()
    .with_tracing()
    .partial(
        groupers=groupers,
        group_column="Station",
        category_column="Observation Category 0",
        match_values=["mangrove logging", "poaching", "arrests", "poached turtle sum"],
        pivot_on="group",
        date_column=None,
        top_n=None,
        exclude_values=None,
        colors=None,
        remap_column="Resource Use Type",
        remap_value="illegal use",
        remap_label="illegal fishing",
        filter_column="Station",
        filter_value="Sector",
        group_order=[
            "Sector 1",
            "Sector 2",
            "Sector 3",
            "Sector 4",
            "Sector 5",
            "Sector 6",
            "Sector 7",
            "Sector 8",
            "Sector 9",
            "Sector 10",
            "Sector 11",
            "Sector 12",
            "Sector 13",
        ],
        chart_title="Illegal Events by Sector and Activity Type",
        x_axis_label="Sector",
        y_axis_label="Number of Illegal Events",
        widget_id="Illegal Events by Sector",
        **illegal_events_by_sector_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_data)
)


# %% [markdown]
# ## Persist illegal events by sector HTML

# %%
# parameters

persist_illegal_sector_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_illegal_sector_html = (
    persist_text.set_task_instance_id("persist_illegal_sector_html")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="illegal_events_by_sector",
        **persist_illegal_sector_html_params,
    )
    .mapvalues(argnames=["text"], argvalues=illegal_events_by_sector)
)


# %% [markdown]
# ## Convert illegal events by sector HTML to PNG

# %%
# parameters

png_illegal_sector_params = dict()

# %%
# call the task


png_illegal_sector = (
    html_to_png.set_task_instance_id("png_illegal_sector")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_illegal_sector_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_illegal_sector_html)
)


# %% [markdown]
# ## Create illegal events by sector widget

# %%
# parameters

illegal_events_sector_widget_params = dict(
    view=...,
)

# %%
# call the task


illegal_events_sector_widget = (
    create_plot_widget_single_view.set_task_instance_id("illegal_events_sector_widget")
    .handle_errors()
    .with_tracing()
    .partial(title="Illegal Events by Sector", **illegal_events_sector_widget_params)
    .mapvalues(argnames=["data"], argvalues=persist_illegal_sector_html)
)


# %% [markdown]
# ## Draw village proportional chart

# %%
# parameters

village_proportional_chart_params = dict()

# %%
# call the task


village_proportional_chart = (
    draw_proportional_bar_chart.set_task_instance_id("village_proportional_chart")
    .handle_errors()
    .with_tracing()
    .partial(
        groupers=groupers,
        group_column="Village",
        metrics=[
            {
                "label": "Number of Patrols",
                "column": "Patrol ID",
                "aggregation": "nunique",
            },
            {"label": "Patrol Hours", "column": "Patrol ID", "aggregation": "nunique"},
            {
                "label": "Total Events",
                "column": "Observation Category 0",
                "aggregation": "count",
            },
        ],
        chart_title="Per Village Patrol Proportions",
        widget_id="Village Patrol Proportions",
        filter_column=None,
        filter_value=None,
        colors=None,
        **village_proportional_chart_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_data)
)


# %% [markdown]
# ## Persist village proportional chart HTML

# %%
# parameters

persist_village_prop_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_village_prop_html = (
    persist_text.set_task_instance_id("persist_village_prop_html")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="village_proportional",
        **persist_village_prop_html_params,
    )
    .mapvalues(argnames=["text"], argvalues=village_proportional_chart)
)


# %% [markdown]
# ## Convert village proportional chart HTML to PNG

# %%
# parameters

html_to_png_village_proportional_params = dict()

# %%
# call the task


html_to_png_village_proportional = (
    html_to_png.set_task_instance_id("html_to_png_village_proportional")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **html_to_png_village_proportional_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_village_prop_html)
)


# %% [markdown]
# ## Create village proportional widget

# %%
# parameters

village_proportional_widget_params = dict(
    view=...,
)

# %%
# call the task


village_proportional_widget = (
    create_plot_widget_single_view.set_task_instance_id("village_proportional_widget")
    .handle_errors()
    .with_tracing()
    .partial(title="Village Patrol Proportions", **village_proportional_widget_params)
    .mapvalues(argnames=["data"], argvalues=persist_village_prop_html)
)


# %% [markdown]
# ## Prepare arrests by village data

# %%
# parameters

arrests_by_village_data_params = dict()

# %%
# call the task


arrests_by_village_data = (
    prepare_grouped_summary.set_task_instance_id("arrests_by_village_data")
    .handle_errors()
    .with_tracing()
    .partial(
        df=clean_data,
        groupers=groupers,
        group_column="Village",
        aggregations={"Arrest_Count": "Observation Category 0:count"},
        most_recent_period_only=False,
        derived_columns=None,
        group_values=None,
        station_column=None,
        station_filter=None,
        **arrests_by_village_data_params,
    )
    .call()
)


# %% [markdown]
# ## Draw arrests by village chart

# %%
# parameters

arrests_by_village_chart_params = dict()

# %%
# call the task


arrests_by_village_chart = (
    draw_bar_chart.set_task_instance_id("arrests_by_village_chart")
    .handle_errors()
    .with_tracing()
    .partial(
        dataframe=arrests_by_village_data,
        category="Village",
        bar_chart_configs=[
            {
                "column": "Arrest_Count",
                "agg_func": "sum",
                "label": "Arrests",
                "text": "Arrest_Count",
                "textposition": "outside",
                "textfont_size": 10,
            }
        ],
        layout_kwargs={
            "title": "Number of Arrests by Village",
            "title_x": 0.5,
            "font_size": 12,
            "font_color": "black",
            "yaxis": {"title": "Number of Arrests", "title_font_size": 10},
            "xaxis": {"title": "Village", "title_font_size": 10},
        },
        widget_id="Arrests by Village",
        **arrests_by_village_chart_params,
    )
    .call()
)


# %% [markdown]
# ## Persist arrests by village HTML

# %%
# parameters

persist_arrests_village_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_arrests_village_html = (
    persist_text.set_task_instance_id("persist_arrests_village_html")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="arrests_by_village",
        text=arrests_by_village_chart,
        **persist_arrests_village_html_params,
    )
    .call()
)


# %% [markdown]
# ## Convert arrests by village HTML to PNG

# %%
# parameters

png_arrests_village_params = dict()

# %%
# call the task


png_arrests_village = (
    html_to_png.set_task_instance_id("png_arrests_village")
    .handle_errors()
    .with_tracing()
    .partial(
        html_path=persist_arrests_village_html,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_arrests_village_params,
    )
    .call()
)


# %% [markdown]
# ## Create arrests by village widget

# %%
# parameters

arrests_village_widget_params = dict(
    view=...,
)

# %%
# call the task


arrests_village_widget = (
    create_plot_widget_single_view.set_task_instance_id("arrests_village_widget")
    .handle_errors()
    .with_tracing()
    .partial(
        title="Arrests by Village",
        data=persist_arrests_village_html,
        **arrests_village_widget_params,
    )
    .call()
)


# %% [markdown]
# ## Draw top villages by category chart

# %%
# parameters

top_villages_category_chart_params = dict()

# %%
# call the task


top_villages_category_chart = (
    draw_stacked_bar_chart.set_task_instance_id("top_villages_category_chart")
    .handle_errors()
    .with_tracing()
    .partial(
        groupers=groupers,
        group_column="Village",
        category_column="Observation Category 0",
        match_values=["mangrove logging", "poaching", "poached turtle"],
        remap_column="Resource Use Type",
        remap_value="illegal use",
        remap_label="illegal fishing",
        top_n=5,
        chart_title="Top 5 Villages: Illegal Activities by Category",
        x_axis_label="Illegal Activity Category",
        y_axis_label="Number of Illegal Events",
        widget_id="Top 5 Villages by Category",
        pivot_on="category",
        date_column=None,
        group_order=None,
        exclude_values=None,
        filter_column=None,
        filter_value=None,
        colors=None,
        **top_villages_category_chart_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_data)
)


# %% [markdown]
# ## Persist top villages category HTML

# %%
# parameters

persist_top_villages_cat_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_top_villages_cat_html = (
    persist_text.set_task_instance_id("persist_top_villages_cat_html")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="top_villages_by_category",
        **persist_top_villages_cat_html_params,
    )
    .mapvalues(argnames=["text"], argvalues=top_villages_category_chart)
)


# %% [markdown]
# ## Convert top villages category chart HTML to PNG

# %%
# parameters

png_top_villages_cat_params = dict()

# %%
# call the task


png_top_villages_cat = (
    html_to_png.set_task_instance_id("png_top_villages_cat")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_top_villages_cat_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_top_villages_cat_html)
)


# %% [markdown]
# ## Create top villages category widget

# %%
# parameters

top_villages_category_widget_params = dict(
    view=...,
)

# %%
# call the task


top_villages_category_widget = (
    create_plot_widget_single_view.set_task_instance_id("top_villages_category_widget")
    .handle_errors()
    .with_tracing()
    .partial(title="Top 5 Villages by Category", **top_villages_category_widget_params)
    .mapvalues(argnames=["data"], argvalues=persist_top_villages_cat_html)
)


# %% [markdown]
# ## Draw top villages monthly trend chart

# %%
# parameters

top_villages_monthly_chart_params = dict()

# %%
# call the task


top_villages_monthly_chart = (
    draw_stacked_bar_chart.set_task_instance_id("top_villages_monthly_chart")
    .handle_errors()
    .with_tracing()
    .partial(
        groupers=groupers,
        group_column="Village",
        category_column="Observation Category 0",
        match_values=["mangrove logging", "poaching", "poached turtle"],
        remap_column="Resource Use Type",
        remap_value="illegal use",
        remap_label="illegal fishing",
        top_n=5,
        pivot_on="month",
        date_column="Patrol Start Date",
        chart_title="Top 5 Villages: Illegal Activities Monthly Trend",
        x_axis_label="Month",
        y_axis_label="Number of Illegal Events",
        widget_id="Top 5 Villages Monthly Trend",
        group_order=None,
        exclude_values=None,
        filter_column=None,
        filter_value=None,
        colors=None,
        **top_villages_monthly_chart_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_data)
)


# %% [markdown]
# ## Persist top villages monthly HTML

# %%
# parameters

persist_top_villages_month_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_top_villages_month_html = (
    persist_text.set_task_instance_id("persist_top_villages_month_html")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="top_villages_monthly_trend",
        **persist_top_villages_month_html_params,
    )
    .mapvalues(argnames=["text"], argvalues=top_villages_monthly_chart)
)


# %% [markdown]
# ## Convert top villages monthly chart HTML to PNG

# %%
# parameters

png_top_villages_month_params = dict()

# %%
# call the task


png_top_villages_month = (
    html_to_png.set_task_instance_id("png_top_villages_month")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_top_villages_month_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_top_villages_month_html)
)


# %% [markdown]
# ## Create top villages monthly widget

# %%
# parameters

top_villages_monthly_widget_params = dict(
    view=...,
)

# %%
# call the task


top_villages_monthly_widget = (
    create_plot_widget_single_view.set_task_instance_id("top_villages_monthly_widget")
    .handle_errors()
    .with_tracing()
    .partial(title="Top 5 Villages Monthly Trend", **top_villages_monthly_widget_params)
    .mapvalues(argnames=["data"], argvalues=persist_top_villages_month_html)
)


# %% [markdown]
# ## Draw village monthly timeseries chart

# %%
# parameters

village_monthly_timeseries_chart_params = dict()

# %%
# call the task


village_monthly_timeseries_chart = (
    draw_stacked_bar_chart.set_task_instance_id("village_monthly_timeseries_chart")
    .handle_errors()
    .with_tracing()
    .partial(
        groupers=groupers,
        group_column="Village",
        category_column="Observation Category 0",
        match_values=["mangrove logging", "poaching", "arrests", "poached turtle sum"],
        remap_column="Resource Use Type",
        remap_value="illegal use",
        remap_label="illegal fishing",
        pivot_on="month",
        date_column="Patrol Start Date",
        top_n=5,
        chart_title="Monthly Illegal Activities per Village",
        x_axis_label="Month",
        y_axis_label="Number of Events",
        widget_id="Village Monthly Illegal Activities",
        group_order=None,
        exclude_values=None,
        filter_column=None,
        filter_value=None,
        colors=None,
        **village_monthly_timeseries_chart_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_data)
)


# %% [markdown]
# ## Persist village monthly timeseries HTML

# %%
# parameters

persist_village_monthly_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_village_monthly_html = (
    persist_text.set_task_instance_id("persist_village_monthly_html")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="village_monthly_timeseries",
        **persist_village_monthly_html_params,
    )
    .mapvalues(argnames=["text"], argvalues=village_monthly_timeseries_chart)
)


# %% [markdown]
# ## Convert village monthly timeseries chart HTML to PNG

# %%
# parameters

png_village_month_params = dict()

# %%
# call the task


png_village_month = (
    html_to_png.set_task_instance_id("png_village_month")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 1000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **png_village_month_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_village_monthly_html)
)


# %% [markdown]
# ## Create village monthly timeseries widget

# %%
# parameters

village_monthly_widget_params = dict(
    view=...,
)

# %%
# call the task


village_monthly_widget = (
    create_plot_widget_single_view.set_task_instance_id("village_monthly_widget")
    .handle_errors()
    .with_tracing()
    .partial(
        title="Village Monthly Illegal Activities", **village_monthly_widget_params
    )
    .mapvalues(argnames=["data"], argvalues=persist_village_monthly_html)
)


# %% [markdown]
# ## Draw illegal events hotspot map

# %%
# parameters

illegal_events_map_params = dict()

# %%
# call the task


illegal_events_map = (
    draw_illegal_events_map.set_task_instance_id("illegal_events_map")
    .handle_errors()
    .with_tracing()
    .partial(
        groupers=groupers,
        marine_layers_path=marine_layers_input,
        widget_id="Illegal Events Map",
        **illegal_events_map_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_data)
)


# %% [markdown]
# ## Persist illegal events map HTML

# %%
# parameters

persist_illegal_events_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_illegal_events_html = (
    persist_text.set_task_instance_id("persist_illegal_events_html")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="illegal_events_map",
        **persist_illegal_events_html_params,
    )
    .mapvalues(argnames=["text"], argvalues=illegal_events_map)
)


# %% [markdown]
# ## Convert illegal events map HTML to PNG

# %%
# parameters

html_to_png_illegal_events_map_params = dict()

# %%
# call the task


html_to_png_illegal_events_map = (
    html_to_png.set_task_instance_id("html_to_png_illegal_events_map")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 60000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **html_to_png_illegal_events_map_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_illegal_events_html)
)


# %% [markdown]
# ## Create illegal events map widget

# %%
# parameters

illegal_events_map_widget_params = dict(
    view=...,
)

# %%
# call the task


illegal_events_map_widget = (
    create_map_widget_single_view.set_task_instance_id("illegal_events_map_widget")
    .handle_errors()
    .with_tracing()
    .partial(title="Illegal Events Map", **illegal_events_map_widget_params)
    .mapvalues(argnames=["data"], argvalues=persist_illegal_events_html)
)


# %% [markdown]
# ## Draw weighted patrol effort map

# %%
# parameters

weighted_effort_map_params = dict()

# %%
# call the task


weighted_effort_map = (
    draw_weighted_effort_map.set_task_instance_id("weighted_effort_map")
    .handle_errors()
    .with_tracing()
    .partial(
        groupers=groupers,
        marine_layers_path=marine_layers_input,
        widget_id="Weighted Patrol Effort Map",
        **weighted_effort_map_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_data)
)


# %% [markdown]
# ## Persist weighted effort map HTML

# %%
# parameters

persist_weighted_effort_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_weighted_effort_html = (
    persist_text.set_task_instance_id("persist_weighted_effort_html")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="weighted_effort_map",
        **persist_weighted_effort_html_params,
    )
    .mapvalues(argnames=["text"], argvalues=weighted_effort_map)
)


# %% [markdown]
# ## Convert weighted effort map HTML to PNG

# %%
# parameters

html_to_png_weighted_effort_map_params = dict()

# %%
# call the task


html_to_png_weighted_effort_map = (
    html_to_png.set_task_instance_id("html_to_png_weighted_effort_map")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 60000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **html_to_png_weighted_effort_map_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_weighted_effort_html)
)


# %% [markdown]
# ## Create weighted effort map widget

# %%
# parameters

weighted_effort_map_widget_params = dict(
    view=...,
)

# %%
# call the task


weighted_effort_map_widget = (
    create_map_widget_single_view.set_task_instance_id("weighted_effort_map_widget")
    .handle_errors()
    .with_tracing()
    .partial(title="Weighted Patrol Effort Map", **weighted_effort_map_widget_params)
    .mapvalues(argnames=["data"], argvalues=persist_weighted_effort_html)
)


# %% [markdown]
# ## Draw standardised event rate map

# %%
# parameters

standardized_rate_map_params = dict()

# %%
# call the task


standardized_rate_map = (
    draw_standardized_rate_map.set_task_instance_id("standardized_rate_map")
    .handle_errors()
    .with_tracing()
    .partial(
        groupers=groupers,
        marine_layers_path=marine_layers_input,
        widget_id="Standardised Event Rate Map",
        **standardized_rate_map_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_data)
)


# %% [markdown]
# ## Persist standardised rate map HTML

# %%
# parameters

persist_standardized_rate_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_standardized_rate_html = (
    persist_text.set_task_instance_id("persist_standardized_rate_html")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="standardized_rate_map",
        **persist_standardized_rate_html_params,
    )
    .mapvalues(argnames=["text"], argvalues=standardized_rate_map)
)


# %% [markdown]
# ## Convert standardised rate map HTML to PNG

# %%
# parameters

html_to_png_standardized_rate_params = dict()

# %%
# call the task


html_to_png_standardized_rate = (
    html_to_png.set_task_instance_id("html_to_png_standardized_rate")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 60000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **html_to_png_standardized_rate_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_standardized_rate_html)
)


# %% [markdown]
# ## Create standardised rate map widget

# %%
# parameters

standardized_rate_map_widget_params = dict(
    view=...,
)

# %%
# call the task


standardized_rate_map_widget = (
    create_map_widget_single_view.set_task_instance_id("standardized_rate_map_widget")
    .handle_errors()
    .with_tracing()
    .partial(title="Standardised Event Rate Map", **standardized_rate_map_widget_params)
    .mapvalues(argnames=["data"], argvalues=persist_standardized_rate_html)
)


# %% [markdown]
# ## Draw ecograph patrol effort map

# %%
# parameters

ecograph_map_params = dict()

# %%
# call the task


ecograph_map = (
    draw_ecograph_map.set_task_instance_id("ecograph_map")
    .handle_errors()
    .with_tracing()
    .partial(
        groupers=groupers,
        marine_layers_path=marine_layers_input,
        widget_id="Ecograph Patrol Effort Map",
        **ecograph_map_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_data)
)


# %% [markdown]
# ## Persist ecograph map HTML

# %%
# parameters

persist_ecograph_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_ecograph_html = (
    persist_text.set_task_instance_id("persist_ecograph_html")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="ecograph_map",
        **persist_ecograph_html_params,
    )
    .mapvalues(argnames=["text"], argvalues=ecograph_map)
)


# %% [markdown]
# ## Convert ecograph map HTML to PNG

# %%
# parameters

html_to_png_ecograph_map_params = dict()

# %%
# call the task


html_to_png_ecograph_map = (
    html_to_png.set_task_instance_id("html_to_png_ecograph_map")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 60000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **html_to_png_ecograph_map_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_ecograph_html)
)


# %% [markdown]
# ## Create ecograph map widget

# %%
# parameters

ecograph_map_widget_params = dict(
    view=...,
)

# %%
# call the task


ecograph_map_widget = (
    create_map_widget_single_view.set_task_instance_id("ecograph_map_widget")
    .handle_errors()
    .with_tracing()
    .partial(title="Ecograph Patrol Effort Map", **ecograph_map_widget_params)
    .mapvalues(argnames=["data"], argvalues=persist_ecograph_html)
)


# %% [markdown]
# ## Draw mangrove logging hotspot map

# %%
# parameters

mangrove_logging_map_params = dict()

# %%
# call the task


mangrove_logging_map = (
    draw_mangrove_logging_map.set_task_instance_id("mangrove_logging_map")
    .handle_errors()
    .with_tracing()
    .partial(
        groupers=groupers,
        marine_layers_path=marine_layers_input,
        widget_id="Mangrove Logging Hotspot Map",
        **mangrove_logging_map_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_data)
)


# %% [markdown]
# ## Persist mangrove logging map HTML

# %%
# parameters

persist_mangrove_logging_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_mangrove_logging_html = (
    persist_text.set_task_instance_id("persist_mangrove_logging_html")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="mangrove_logging_map",
        **persist_mangrove_logging_html_params,
    )
    .mapvalues(argnames=["text"], argvalues=mangrove_logging_map)
)


# %% [markdown]
# ## Convert mangrove logging map HTML to PNG

# %%
# parameters

html_to_png_mangrove_logging_params = dict()

# %%
# call the task


html_to_png_mangrove_logging = (
    html_to_png.set_task_instance_id("html_to_png_mangrove_logging")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 60000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **html_to_png_mangrove_logging_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_mangrove_logging_html)
)


# %% [markdown]
# ## Create mangrove logging map widget

# %%
# parameters

mangrove_logging_map_widget_params = dict(
    view=...,
)

# %%
# call the task


mangrove_logging_map_widget = (
    create_map_widget_single_view.set_task_instance_id("mangrove_logging_map_widget")
    .handle_errors()
    .with_tracing()
    .partial(title="Mangrove Logging Hotspot Map", **mangrove_logging_map_widget_params)
    .mapvalues(argnames=["data"], argvalues=persist_mangrove_logging_html)
)


# %% [markdown]
# ## Draw poaching hotspot map

# %%
# parameters

poaching_map_params = dict()

# %%
# call the task


poaching_map = (
    draw_poaching_map.set_task_instance_id("poaching_map")
    .handle_errors()
    .with_tracing()
    .partial(
        groupers=groupers,
        marine_layers_path=marine_layers_input,
        widget_id="Poaching Hotspot Map",
        **poaching_map_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_data)
)


# %% [markdown]
# ## Persist poaching map HTML

# %%
# parameters

persist_poaching_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_poaching_html = (
    persist_text.set_task_instance_id("persist_poaching_html")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="poaching_map",
        **persist_poaching_html_params,
    )
    .mapvalues(argnames=["text"], argvalues=poaching_map)
)


# %% [markdown]
# ## Convert poaching map HTML to PNG

# %%
# parameters

html_to_png_poaching_params = dict()

# %%
# call the task


html_to_png_poaching = (
    html_to_png.set_task_instance_id("html_to_png_poaching")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 60000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **html_to_png_poaching_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_poaching_html)
)


# %% [markdown]
# ## Create poaching map widget

# %%
# parameters

poaching_map_widget_params = dict(
    view=...,
)

# %%
# call the task


poaching_map_widget = (
    create_map_widget_single_view.set_task_instance_id("poaching_map_widget")
    .handle_errors()
    .with_tracing()
    .partial(title="Poaching Hotspot Map", **poaching_map_widget_params)
    .mapvalues(argnames=["data"], argvalues=persist_poaching_html)
)


# %% [markdown]
# ## Draw illegal fishing hotspot map

# %%
# parameters

illegal_fishing_map_params = dict()

# %%
# call the task


illegal_fishing_map = (
    draw_illegal_fishing_map.set_task_instance_id("illegal_fishing_map")
    .handle_errors()
    .with_tracing()
    .partial(
        groupers=groupers,
        marine_layers_path=marine_layers_input,
        widget_id="Illegal Fishing Hotspot Map",
        **illegal_fishing_map_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_data)
)


# %% [markdown]
# ## Persist illegal fishing map HTML

# %%
# parameters

persist_illegal_fishing_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_illegal_fishing_html = (
    persist_text.set_task_instance_id("persist_illegal_fishing_html")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="illegal_fishing_map",
        **persist_illegal_fishing_html_params,
    )
    .mapvalues(argnames=["text"], argvalues=illegal_fishing_map)
)


# %% [markdown]
# ## Convert illegal fishing map HTML to PNG

# %%
# parameters

html_to_png_illegal_fishing_params = dict()

# %%
# call the task


html_to_png_illegal_fishing = (
    html_to_png.set_task_instance_id("html_to_png_illegal_fishing")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 60000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **html_to_png_illegal_fishing_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_illegal_fishing_html)
)


# %% [markdown]
# ## Create illegal fishing map widget

# %%
# parameters

illegal_fishing_map_widget_params = dict(
    view=...,
)

# %%
# call the task


illegal_fishing_map_widget = (
    create_map_widget_single_view.set_task_instance_id("illegal_fishing_map_widget")
    .handle_errors()
    .with_tracing()
    .partial(title="Illegal Fishing Hotspot Map", **illegal_fishing_map_widget_params)
    .mapvalues(argnames=["data"], argvalues=persist_illegal_fishing_html)
)


# %% [markdown]
# ## Draw arrests hotspot map

# %%
# parameters

arrests_map_params = dict()

# %%
# call the task


arrests_map = (
    draw_arrests_map.set_task_instance_id("arrests_map")
    .handle_errors()
    .with_tracing()
    .partial(
        groupers=groupers,
        marine_layers_path=marine_layers_input,
        widget_id="Arrests Hotspot Map",
        **arrests_map_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_data)
)


# %% [markdown]
# ## Persist arrests map HTML

# %%
# parameters

persist_arrests_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_arrests_html = (
    persist_text.set_task_instance_id("persist_arrests_html")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="arrests_map",
        **persist_arrests_html_params,
    )
    .mapvalues(argnames=["text"], argvalues=arrests_map)
)


# %% [markdown]
# ## Convert arrests map HTML to PNG

# %%
# parameters

html_to_png_arrests_params = dict()

# %%
# call the task


html_to_png_arrests = (
    html_to_png.set_task_instance_id("html_to_png_arrests")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 60000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **html_to_png_arrests_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_arrests_html)
)


# %% [markdown]
# ## Create arrests map widget

# %%
# parameters

arrests_map_widget_params = dict(
    view=...,
)

# %%
# call the task


arrests_map_widget = (
    create_map_widget_single_view.set_task_instance_id("arrests_map_widget")
    .handle_errors()
    .with_tracing()
    .partial(title="Arrests Hotspot Map", **arrests_map_widget_params)
    .mapvalues(argnames=["data"], argvalues=persist_arrests_html)
)


# %% [markdown]
# ## Draw poached turtles hotspot map

# %%
# parameters

poached_turtles_map_params = dict()

# %%
# call the task


poached_turtles_map = (
    draw_poached_turtles_map.set_task_instance_id("poached_turtles_map")
    .handle_errors()
    .with_tracing()
    .partial(
        groupers=groupers,
        marine_layers_path=marine_layers_input,
        widget_id="Poached Turtles Hotspot Map",
        **poached_turtles_map_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_data)
)


# %% [markdown]
# ## Persist poached turtles map HTML

# %%
# parameters

persist_poached_turtles_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_poached_turtles_html = (
    persist_text.set_task_instance_id("persist_poached_turtles_html")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="poached_turtles_map",
        **persist_poached_turtles_html_params,
    )
    .mapvalues(argnames=["text"], argvalues=poached_turtles_map)
)


# %% [markdown]
# ## Convert poached turtles map HTML to PNG

# %%
# parameters

html_to_png_poached_turtles_params = dict()

# %%
# call the task


html_to_png_poached_turtles = (
    html_to_png.set_task_instance_id("html_to_png_poached_turtles")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={
            "full_page": False,
            "device_scale_factor": 1.0,
            "wait_for_timeout": 60000,
            "timeout": 0,
            "max_concurrent_pages": 1,
        },
        **html_to_png_poached_turtles_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_poached_turtles_html)
)


# %% [markdown]
# ## Create poached turtles map widget

# %%
# parameters

poached_turtles_map_widget_params = dict(
    view=...,
)

# %%
# call the task


poached_turtles_map_widget = (
    create_map_widget_single_view.set_task_instance_id("poached_turtles_map_widget")
    .handle_errors()
    .with_tracing()
    .partial(title="Poached Turtles Hotspot Map", **poached_turtles_map_widget_params)
    .mapvalues(argnames=["data"], argvalues=persist_poached_turtles_html)
)


# %% [markdown]
# ## Get report year

# %%
# parameters

report_year_params = dict()

# %%
# call the task


report_year = (
    get_report_year.set_task_instance_id("report_year")
    .handle_errors()
    .with_tracing()
    .partial(df=clean_data, groupers=groupers, **report_year_params)
    .call()
)


# %% [markdown]
# ## Get report generation date

# %%
# parameters

report_generation_date_params = dict()

# %%
# call the task


report_generation_date = (
    get_generation_date.set_task_instance_id("report_generation_date")
    .handle_errors()
    .with_tracing()
    .partial(**report_generation_date_params)
    .call()
)


# %% [markdown]
# ## Render patrol summary report

# %%
# parameters

render_patrol_report_params = dict()

# %%
# call the task


render_patrol_report = (
    render_report.set_task_instance_id("render_patrol_report")
    .handle_errors()
    .with_tracing()
    .partial(
        template_path=report_template_input,
        output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        report_year=report_year,
        generation_date=report_generation_date,
        patrol_summary_table=html_to_png_patrol_summary,
        patrol_summary_line=html_to_png_patrols_chart,
        hours_line_chart=html_to_png_hours_chart,
        incidents_line_chart=html_to_png_incidents_chart,
        village_summary_table=html_to_png_village_summary,
        patrol_transport_summary=png_transport_count_chart,
        illegal_activities_summary_dashboard=html_to_png_illegal_activity,
        illegal_activities_doughnut=png_illegal_donut,
        illegal_evidence_text="See charts below for breakdown of illegal activity evidence.",
        mangrove_evidence=png_mangrove_evidence,
        poaching_evidence=png_poaching_evidence,
        illegal_fishing_evidence=html_to_png_fishing_gear_chart,
        village_stacked_bar=png_illegal_sector,
        arrests_by_village_bar=png_arrests_village,
        horizontal_proportional_dashboard=html_to_png_village_proportional,
        all_illegal_hotspot=html_to_png_illegal_events_map,
        mangrove_logging_hotspot=html_to_png_mangrove_logging,
        poaching_hotspot=html_to_png_poaching,
        illegal_fishing_hotspot=html_to_png_illegal_fishing,
        arrests_hotspot=html_to_png_arrests,
        poached_turtles_hotspot=html_to_png_poached_turtles,
        weighted_effort_ecomap=html_to_png_weighted_effort_map,
        standardized_rate_ecomap=html_to_png_standardized_rate,
        ecograph_rate_ecomap=html_to_png_ecograph_map,
        patrol_effort_stacked_bar=png_transport_hours_chart,
        patrol_effort_line=html_to_png_patrol_effort_chart,
        top_villages_by_category=png_top_villages_cat,
        top_villages_monthly_trend=png_top_villages_month,
        violations_over_time_note="Monthly illegal activity charts generated per village for the selected period.",
        **render_patrol_report_params,
    )
    .call()
)


# %% [markdown]
# ## Merge grouped widgets

# %%
# parameters

grouped_widgets_params = dict()

# %%
# call the task


grouped_widgets = (
    groupbykey.set_task_instance_id("grouped_widgets")
    .handle_errors()
    .with_tracing()
    .partial(
        iterables=[
            illegal_activity_donut_widget,
            illegal_events_sector_widget,
            village_proportional_widget,
            top_villages_category_widget,
            top_villages_monthly_widget,
            village_monthly_widget,
            illegal_events_map_widget,
            weighted_effort_map_widget,
            standardized_rate_map_widget,
            ecograph_map_widget,
            mangrove_logging_map_widget,
            poaching_map_widget,
            illegal_fishing_map_widget,
            arrests_map_widget,
            poached_turtles_map_widget,
        ],
        **grouped_widgets_params,
    )
    .call()
)


# %% [markdown]
# ## Assemble dashboard widgets

# %%
# parameters

dashboard_widgets_params = dict()

# %%
# call the task


dashboard_widgets = (
    assemble_dashboard_widgets.set_task_instance_id("dashboard_widgets")
    .handle_errors()
    .with_tracing()
    .partial(
        single_view_widgets=[
            patrol_summary_widget,
            patrols_chart_widget,
            hours_chart_widget,
            incidents_chart_widget,
            village_summary_widget,
            patrol_effort_widget,
            patrol_transport_count_widget,
            patrol_transport_hours_widget,
            illegal_activity_widget,
            mangrove_evidence_widget,
            poaching_evidence_widget,
            fishing_gear_widget,
            arrests_village_widget,
        ],
        keyed_widgets=grouped_widgets,
        **dashboard_widgets_params,
    )
    .call()
)


# %% [markdown]
# ## Patrol Summary Dashboard

# %%
# parameters

patrol_summary_dashboard_params = dict(
    warning=...,
)

# %%
# call the task


patrol_summary_dashboard = (
    gather_dashboard.set_task_instance_id("patrol_summary_dashboard")
    .handle_errors()
    .with_tracing()
    .partial(
        widgets=dashboard_widgets,
        details=workflow_details,
        groupers=groupers,
        time_range=time_range,
        **patrol_summary_dashboard_params,
    )
    .call()
)
