# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import groupbykey as groupbykey
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_ext_bahari_hai.tasks import (
    assemble_dashboard_widgets as assemble_dashboard_widgets,
)
from ecoscope_workflows_ext_bahari_hai.tasks import clean_dataframe as clean_dataframe
from ecoscope_workflows_ext_bahari_hai.tasks import draw_arrests_map as draw_arrests_map
from ecoscope_workflows_ext_bahari_hai.tasks import draw_donut_chart as draw_donut_chart
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_ecograph_map as draw_ecograph_map,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_illegal_events_map as draw_illegal_events_map,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_illegal_fishing_map as draw_illegal_fishing_map,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_mangrove_logging_map as draw_mangrove_logging_map,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_poached_turtles_map as draw_poached_turtles_map,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_poaching_map as draw_poaching_map,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_proportional_bar_chart as draw_proportional_bar_chart,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_stacked_bar_chart as draw_stacked_bar_chart,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_standardized_rate_map as draw_standardized_rate_map,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_summary_dashboard as draw_summary_dashboard,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    draw_weighted_effort_map as draw_weighted_effort_map,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    get_generation_date as get_generation_date,
)
from ecoscope_workflows_ext_bahari_hai.tasks import get_report_year as get_report_year
from ecoscope_workflows_ext_bahari_hai.tasks import (
    prepare_category_counts as prepare_category_counts,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    prepare_grouped_summary as prepare_grouped_summary,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    prepare_pivot_summary as prepare_pivot_summary,
)
from ecoscope_workflows_ext_bahari_hai.tasks import render_report as render_report
from ecoscope_workflows_ext_bahari_hai.tasks import (
    summarize_by_village as summarize_by_village,
)
from ecoscope_workflows_ext_bahari_hai.tasks import (
    summarize_patrols as summarize_patrols,
)
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_custom.tasks.io import load_df as load_df
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_bar_chart as draw_bar_chart,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_line_chart as draw_line_chart,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_table as draw_table
from ecoscope_workflows_ext_ste.tasks import (
    fetch_and_persist_file as fetch_and_persist_file,
)

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        set_workflow_details.validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        set_time_range.validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("time_range") or {}))
        .call()
    )

    csv_input = (
        fetch_and_persist_file.validate()
        .set_task_instance_id("csv_input")
        .handle_errors()
        .with_tracing()
        .partial(
            url="https://raw.githubusercontent.com/wildlife-dynamics/wt-bh-village-games/ae1f5bfb247c0bdde169caaaaf4e5c96cafb6b75/data/patrol_findings_with_village.csv",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            unzip=False,
            retries=3,
            overwrite_existing=False,
            **(params_dict.get("csv_input") or {}),
        )
        .call()
    )

    load_data = (
        load_df.validate()
        .set_task_instance_id("load_data")
        .handle_errors()
        .with_tracing()
        .partial(
            file_path=csv_input,
            layer="landDx_polygons",
            deserialize_json=False,
            **(params_dict.get("load_data") or {}),
        )
        .call()
    )

    marine_layers_input = (
        fetch_and_persist_file.validate()
        .set_task_instance_id("marine_layers_input")
        .handle_errors()
        .with_tracing()
        .partial(
            url="https://drive.google.com/uc?export=download&id=1pNu0xS9lMN-O4SPpSiBihYcUTOGwN5_H",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            unzip=True,
            retries=3,
            overwrite_existing=False,
            **(params_dict.get("marine_layers_input") or {}),
        )
        .call()
    )

    report_template_input = (
        fetch_and_persist_file.validate()
        .set_task_instance_id("report_template_input")
        .handle_errors()
        .with_tracing()
        .partial(
            url="https://docs.google.com/document/d/1qqy2OdAL_RJirep78TlCOBxHL4e6W--5/export?format=docx",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            unzip=False,
            retries=3,
            overwrite_existing=False,
            **(params_dict.get("report_template_input") or {}),
        )
        .call()
    )

    clean_data = (
        clean_dataframe.validate()
        .set_task_instance_id("clean_data")
        .handle_errors()
        .with_tracing()
        .partial(
            data=load_data,
            date_columns=["Patrol Start Date", "Waypoint Date"],
            date_format="%d-%b-%y",
            groupby_period=["Year", "Month", "Quarter"],
            numeric_columns=["X", "Y"],
            drop_duplicates=False,
            **(params_dict.get("clean_data") or {}),
        )
        .call()
    )

    groupers = (
        set_groupers.validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("groupers") or {}))
        .call()
    )

    split_data = (
        split_groups.validate()
        .set_task_instance_id("split_data")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data, groupers=groupers, **(params_dict.get("split_data") or {})
        )
        .call()
    )

    patrol_summaries_by_year = (
        summarize_patrols.validate()
        .set_task_instance_id("patrol_summaries_by_year")
        .handle_errors()
        .with_tracing()
        .partial(df=clean_data, **(params_dict.get("patrol_summaries_by_year") or {}))
        .call()
    )

    patrol_summary_table = (
        draw_table.validate()
        .set_task_instance_id("patrol_summary_table")
        .handle_errors()
        .with_tracing()
        .partial(
            dataframe=patrol_summaries_by_year,
            columns=["Year", "patrols", "hours", "incidents"],
            widget_id="Patrol summaries",
            table_config={
                "enable_sorting": True,
                "enable_filtering": False,
                "enable_download": False,
                "hide_header": False,
            },
            **(params_dict.get("patrol_summary_table") or {}),
        )
        .call()
    )

    persist_patrol_summary_html = (
        persist_text.validate()
        .set_task_instance_id("persist_patrol_summary_html")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="patrol_summary",
            text=patrol_summary_table,
            **(params_dict.get("persist_patrol_summary_html") or {}),
        )
        .call()
    )

    html_to_png_patrol_summary = (
        html_to_png.validate()
        .set_task_instance_id("html_to_png_patrol_summary")
        .handle_errors()
        .with_tracing()
        .partial(
            html_path=persist_patrol_summary_html,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("html_to_png_patrol_summary") or {}),
        )
        .call()
    )

    patrol_summary_widget = (
        create_table_widget_single_view.validate()
        .set_task_instance_id("patrol_summary_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Patrol summaries",
            data=persist_patrol_summary_html,
            **(params_dict.get("patrol_summary_widget") or {}),
        )
        .call()
    )

    patrols_line_chart = (
        draw_line_chart.validate()
        .set_task_instance_id("patrols_line_chart")
        .handle_errors()
        .with_tracing()
        .partial(
            dataframe=patrol_summaries_by_year,
            x_column="Year",
            y_column="patrols",
            category_column=None,
            widget_id="Patrols per Year",
            smoothing=None,
            layout_kwargs={
                "title": "Number of Patrols per Year",
                "title_x": 0.5,
                "font_size": 12.0,
                "font_color": "black",
                "font_family": "Arial",
                "yaxis": {
                    "title": "Number of Patrols",
                    "tick_font_size": 8,
                    "title_font_size": 10,
                },
                "xaxis": {
                    "title": "Year",
                    "tick_font_size": 8,
                    "title_font_size": 10,
                    "tickmode": "linear",
                    "dtick": 1,
                },
                "margin": {"t": 120, "b": 80, "l": 80, "r": 40},
            },
            line_kwargs={
                "color": "#2c3e50",
                "width": 3,
                "shape": "linear",
                "show_markers": True,
            },
            **(params_dict.get("patrols_line_chart") or {}),
        )
        .call()
    )

    persist_patrols_chart_html = (
        persist_text.validate()
        .set_task_instance_id("persist_patrols_chart_html")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="patrols_per_year",
            text=patrols_line_chart,
            **(params_dict.get("persist_patrols_chart_html") or {}),
        )
        .call()
    )

    html_to_png_patrols_chart = (
        html_to_png.validate()
        .set_task_instance_id("html_to_png_patrols_chart")
        .handle_errors()
        .with_tracing()
        .partial(
            html_path=persist_patrols_chart_html,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("html_to_png_patrols_chart") or {}),
        )
        .call()
    )

    patrols_chart_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("patrols_chart_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Patrols per Year",
            data=persist_patrols_chart_html,
            **(params_dict.get("patrols_chart_widget") or {}),
        )
        .call()
    )

    hours_line_chart = (
        draw_line_chart.validate()
        .set_task_instance_id("hours_line_chart")
        .handle_errors()
        .with_tracing()
        .partial(
            dataframe=patrol_summaries_by_year,
            x_column="Year",
            y_column="hours",
            category_column=None,
            widget_id="Patrol Hours per Year",
            smoothing=None,
            layout_kwargs={
                "title": "Patrol Hours per Year",
                "title_x": 0.5,
                "font_size": 12.0,
                "font_color": "black",
                "font_family": "Arial",
                "yaxis": {
                    "title": "Patrol Hours",
                    "tick_font_size": 8,
                    "title_font_size": 10,
                },
                "xaxis": {
                    "title": "Year",
                    "tick_font_size": 8,
                    "title_font_size": 10,
                    "tickmode": "linear",
                    "dtick": 1,
                },
                "margin": {"t": 120, "b": 80, "l": 80, "r": 40},
            },
            line_kwargs={
                "color": "#2c3e50",
                "width": 3,
                "shape": "linear",
                "show_markers": True,
            },
            **(params_dict.get("hours_line_chart") or {}),
        )
        .call()
    )

    persist_hours_chart_html = (
        persist_text.validate()
        .set_task_instance_id("persist_hours_chart_html")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="patrol_hours_per_year",
            text=hours_line_chart,
            **(params_dict.get("persist_hours_chart_html") or {}),
        )
        .call()
    )

    html_to_png_hours_chart = (
        html_to_png.validate()
        .set_task_instance_id("html_to_png_hours_chart")
        .handle_errors()
        .with_tracing()
        .partial(
            html_path=persist_hours_chart_html,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("html_to_png_hours_chart") or {}),
        )
        .call()
    )

    hours_chart_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("hours_chart_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Patrol Hours per Year",
            data=persist_hours_chart_html,
            **(params_dict.get("hours_chart_widget") or {}),
        )
        .call()
    )

    incidents_line_chart = (
        draw_line_chart.validate()
        .set_task_instance_id("incidents_line_chart")
        .handle_errors()
        .with_tracing()
        .partial(
            dataframe=patrol_summaries_by_year,
            x_column="Year",
            y_column="incidents",
            category_column=None,
            widget_id="Incidents per Year",
            smoothing=None,
            layout_kwargs={
                "title": "Number of Incidents per Year",
                "title_x": 0.5,
                "font_size": 12,
                "font_color": "black",
                "font_family": "Arial",
                "yaxis": {
                    "title": "Number of Incidents",
                    "tick_font_size": 8,
                    "title_font_size": 10,
                },
                "xaxis": {
                    "title": "Year",
                    "tick_font_size": 8,
                    "title_font_size": 10,
                    "tickmode": "linear",
                    "dtick": 1,
                },
                "margin": {"t": 120, "b": 80, "l": 80, "r": 40},
            },
            line_kwargs={
                "color": "#2c3e50",
                "width": 3,
                "shape": "linear",
                "show_markers": True,
                "smoothing": False,
            },
            **(params_dict.get("incidents_line_chart") or {}),
        )
        .call()
    )

    persist_incidents_chart_html = (
        persist_text.validate()
        .set_task_instance_id("persist_incidents_chart_html")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="incidents_per_year",
            text=incidents_line_chart,
            **(params_dict.get("persist_incidents_chart_html") or {}),
        )
        .call()
    )

    html_to_png_incidents_chart = (
        html_to_png.validate()
        .set_task_instance_id("html_to_png_incidents_chart")
        .handle_errors()
        .with_tracing()
        .partial(
            html_path=persist_incidents_chart_html,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("html_to_png_incidents_chart") or {}),
        )
        .call()
    )

    incidents_chart_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("incidents_chart_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Incidents per Year",
            data=persist_incidents_chart_html,
            **(params_dict.get("incidents_chart_widget") or {}),
        )
        .call()
    )

    village_summaries = (
        summarize_by_village.validate()
        .set_task_instance_id("village_summaries")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            groupers=groupers,
            **(params_dict.get("village_summaries") or {}),
        )
        .call()
    )

    village_summary_table = (
        draw_table.validate()
        .set_task_instance_id("village_summary_table")
        .handle_errors()
        .with_tracing()
        .partial(
            dataframe=village_summaries,
            columns=[
                "Village",
                "Number Of Patrols",
                "Total Patrol Hours",
                "Mangrove Logging",
                "Poaching",
                "Illegal Fishing",
                "Damaging Coral",
                "Arrests",
            ],
            widget_id="Village Patrol Summary",
            table_config={
                "enable_sorting": True,
                "enable_filtering": False,
                "enable_download": False,
                "hide_header": False,
            },
            **(params_dict.get("village_summary_table") or {}),
        )
        .call()
    )

    persist_village_summary_html = (
        persist_text.validate()
        .set_task_instance_id("persist_village_summary_html")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="village_summary",
            text=village_summary_table,
            **(params_dict.get("persist_village_summary_html") or {}),
        )
        .call()
    )

    html_to_png_village_summary = (
        html_to_png.validate()
        .set_task_instance_id("html_to_png_village_summary")
        .handle_errors()
        .with_tracing()
        .partial(
            html_path=persist_village_summary_html,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("html_to_png_village_summary") or {}),
        )
        .call()
    )

    village_summary_widget = (
        create_table_widget_single_view.validate()
        .set_task_instance_id("village_summary_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Village Patrol Summary",
            data=persist_village_summary_html,
            **(params_dict.get("village_summary_widget") or {}),
        )
        .call()
    )

    patrol_effort_data = (
        prepare_pivot_summary.validate()
        .set_task_instance_id("patrol_effort_data")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            groupers=groupers,
            pivot_column="Patrol Transport Type",
            value_column="Patrol ID",
            aggregation="nunique",
            multiplier=8.0,
            pivot_values=["Boat", "Foot", "Vehicle"],
            station_column="Station",
            station_filter="Sector",
            **(params_dict.get("patrol_effort_data") or {}),
        )
        .call()
    )

    patrol_effort_chart = (
        draw_bar_chart.validate()
        .set_task_instance_id("patrol_effort_chart")
        .handle_errors()
        .with_tracing()
        .partial(
            dataframe=patrol_effort_data,
            category="Year",
            bar_chart_configs=[
                {"column": "Boat", "agg_func": "sum", "label": "Boat"},
                {"column": "Foot", "agg_func": "sum", "label": "Foot"},
                {"column": "Vehicle", "agg_func": "sum", "label": "Vehicle"},
            ],
            layout_kwargs={
                "title": "Patrol Effort by Transport Type",
                "title_x": 0.5,
                "font_size": 12,
                "font_color": "black",
                "font_family": "Arial",
                "yaxis": {
                    "title": "Patrol Hours",
                    "tick_font_size": 8,
                    "title_font_size": 10,
                },
                "xaxis": {
                    "title": "Period",
                    "tick_font_size": 8,
                    "title_font_size": 10,
                },
            },
            widget_id="Patrol Effort by Transport Type",
            **(params_dict.get("patrol_effort_chart") or {}),
        )
        .call()
    )

    persist_patrol_effort_html = (
        persist_text.validate()
        .set_task_instance_id("persist_patrol_effort_html")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="patrol_effort",
            text=patrol_effort_chart,
            **(params_dict.get("persist_patrol_effort_html") or {}),
        )
        .call()
    )

    html_to_png_patrol_effort_chart = (
        html_to_png.validate()
        .set_task_instance_id("html_to_png_patrol_effort_chart")
        .handle_errors()
        .with_tracing()
        .partial(
            html_path=persist_patrol_effort_html,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("html_to_png_patrol_effort_chart") or {}),
        )
        .call()
    )

    patrol_effort_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("patrol_effort_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Patrol Effort by Transport Type",
            data=persist_patrol_effort_html,
            **(params_dict.get("patrol_effort_widget") or {}),
        )
        .call()
    )

    patrol_transport_data = (
        prepare_grouped_summary.validate()
        .set_task_instance_id("patrol_transport_data")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            groupers=groupers,
            group_column="Patrol Transport Type",
            aggregations={"Patrol Count": "Patrol ID:nunique"},
            derived_columns={"Patrol Hours": "Patrol Count * 8.0"},
            group_values=["Boat", "Foot", "Vehicle"],
            station_column="Station",
            station_filter="Sector",
            most_recent_period_only=False,
            **(params_dict.get("patrol_transport_data") or {}),
        )
        .call()
    )

    patrol_transport_count_chart = (
        draw_bar_chart.validate()
        .set_task_instance_id("patrol_transport_count_chart")
        .handle_errors()
        .with_tracing()
        .partial(
            dataframe=patrol_transport_data,
            category="Patrol Transport Type",
            bar_chart_configs=[
                {
                    "column": "Patrol Count",
                    "agg_func": "sum",
                    "label": "Count",
                    "text": "Patrol Count",
                    "textposition": "outside",
                    "textfont_size": 12,
                }
            ],
            layout_kwargs={
                "title": "Number of Patrols by Transport Type",
                "title_x": 0.5,
                "font_size": 12,
                "font_color": "black",
                "font_family": "Arial",
                "yaxis": {
                    "title": "Number of Patrols",
                    "title_font_size": 10,
                    "tick_font_size": 8,
                },
                "xaxis": {
                    "title": "Transport Type",
                    "title_font_size": 10,
                    "tick_font_size": 8,
                },
                "margin": {"t": 140, "b": 120, "l": 100, "r": 100},
            },
            widget_id="Patrol Count by Transport Type",
            **(params_dict.get("patrol_transport_count_chart") or {}),
        )
        .call()
    )

    persist_transport_count_html = (
        persist_text.validate()
        .set_task_instance_id("persist_transport_count_html")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="transport_patrol_count",
            text=patrol_transport_count_chart,
            **(params_dict.get("persist_transport_count_html") or {}),
        )
        .call()
    )

    png_transport_count_chart = (
        html_to_png.validate()
        .set_task_instance_id("png_transport_count_chart")
        .handle_errors()
        .with_tracing()
        .partial(
            html_path=persist_transport_count_html,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_transport_count_chart") or {}),
        )
        .call()
    )

    patrol_transport_count_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("patrol_transport_count_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Patrol Count by Transport Type",
            data=persist_transport_count_html,
            **(params_dict.get("patrol_transport_count_widget") or {}),
        )
        .call()
    )

    patrol_transport_hours_chart = (
        draw_bar_chart.validate()
        .set_task_instance_id("patrol_transport_hours_chart")
        .handle_errors()
        .with_tracing()
        .partial(
            dataframe=patrol_transport_data,
            category="Patrol Transport Type",
            bar_chart_configs=[
                {
                    "column": "Patrol Hours",
                    "agg_func": "sum",
                    "label": "Hours",
                    "text": "Patrol Hours",
                    "textposition": "outside",
                    "textfont_size": 12,
                }
            ],
            layout_kwargs={
                "title": "Number of patrol hours by transport type",
                "title_x": 0.5,
                "font_size": 12,
                "font_color": "black",
                "font_family": "Arial",
                "yaxis": {
                    "title": "Patrol Hours",
                    "title_font_size": 10,
                    "tick_font_size": 8,
                },
                "xaxis": {
                    "title": "Transport Type",
                    "title_font_size": 10,
                    "tick_font_size": 8,
                },
                "margin": {"t": 140, "b": 120, "l": 100, "r": 100},
            },
            widget_id="Patrol Hours by Transport Type",
            **(params_dict.get("patrol_transport_hours_chart") or {}),
        )
        .call()
    )

    persist_transport_hours_html = (
        persist_text.validate()
        .set_task_instance_id("persist_transport_hours_html")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="transport_patrol_hours",
            text=patrol_transport_hours_chart,
            **(params_dict.get("persist_transport_hours_html") or {}),
        )
        .call()
    )

    png_transport_hours_chart = (
        html_to_png.validate()
        .set_task_instance_id("png_transport_hours_chart")
        .handle_errors()
        .with_tracing()
        .partial(
            html_path=persist_transport_hours_html,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_transport_hours_chart") or {}),
        )
        .call()
    )

    patrol_transport_hours_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("patrol_transport_hours_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Patrol Hours by Transport Type",
            data=persist_transport_hours_html,
            **(params_dict.get("patrol_transport_hours_widget") or {}),
        )
        .call()
    )

    illegal_activity_summary = (
        draw_summary_dashboard.validate()
        .set_task_instance_id("illegal_activity_summary")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            groupers=groupers,
            category_column="Observation Category 0",
            categories=[
                "Mangrove Logging",
                "Poaching",
                "Arrests",
                "Damaging Coral",
                "Illegal Fishing",
            ],
            filter_column="Station",
            filter_value="Sector",
            sum_columns={"Poached Turtle Sum": "Sum"},
            chart_title="Illegal Activity Summary",
            n_cols=3,
            widget_id="Illegal Activity Summary",
            **(params_dict.get("illegal_activity_summary") or {}),
        )
        .call()
    )

    persist_illegal_activity_html = (
        persist_text.validate()
        .set_task_instance_id("persist_illegal_activity_html")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="illegal_activity_summary",
            text=illegal_activity_summary,
            **(params_dict.get("persist_illegal_activity_html") or {}),
        )
        .call()
    )

    html_to_png_illegal_activity = (
        html_to_png.validate()
        .set_task_instance_id("html_to_png_illegal_activity")
        .handle_errors()
        .with_tracing()
        .partial(
            html_path=persist_illegal_activity_html,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("html_to_png_illegal_activity") or {}),
        )
        .call()
    )

    illegal_activity_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("illegal_activity_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Illegal Activity Summary",
            data=persist_illegal_activity_html,
            **(params_dict.get("illegal_activity_widget") or {}),
        )
        .call()
    )

    illegal_activity_donut = (
        draw_donut_chart.validate()
        .set_task_instance_id("illegal_activity_donut")
        .handle_errors()
        .with_tracing()
        .partial(
            groupers=groupers,
            category_column="Observation Category 0",
            categories=["Mangrove Logging", "Poaching", "Arrests"],
            filter_column="Station",
            filter_value="Sector",
            sum_columns={"Poached Turtle Sum": "Sum"},
            chart_title="Illegal Activities Summary",
            hole=0.4,
            plot_style={
                "marker_colors": [
                    "#1f77b4",
                    "#2ca02c",
                    "#ff7f0e",
                    "#d62728",
                    "#9467bd",
                    "#8c564b",
                ]
            },
            layout_style={
                "showlegend": True,
                "font_size": 8,
                "title_x": 0.5,
                "font_family": "Arial",
                "font_color": "black",
            },
            widget_id="Illegal Activities Donut",
            **(params_dict.get("illegal_activity_donut") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_data)
    )

    persist_illegal_donut_html = (
        persist_text.validate()
        .set_task_instance_id("persist_illegal_donut_html")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="illegal_activity_donut",
            **(params_dict.get("persist_illegal_donut_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=illegal_activity_donut)
    )

    png_illegal_donut = (
        html_to_png.validate()
        .set_task_instance_id("png_illegal_donut")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_illegal_donut") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_illegal_donut_html)
    )

    illegal_activity_donut_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("illegal_activity_donut_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Illegal Activities Donut",
            **(params_dict.get("illegal_activity_donut_widget") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_illegal_donut_html)
    )

    mangrove_evidence_data = (
        prepare_category_counts.validate()
        .set_task_instance_id("mangrove_evidence_data")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            groupers=groupers,
            count_column="Evidence",
            filter_column="Observation Category 0",
            filter_value="mangrove logging",
            station_column="Station",
            station_filter="Sector",
            exclude_values=None,
            **(params_dict.get("mangrove_evidence_data") or {}),
        )
        .call()
    )

    mangrove_evidence_chart = (
        draw_bar_chart.validate()
        .set_task_instance_id("mangrove_evidence_chart")
        .handle_errors()
        .with_tracing()
        .partial(
            dataframe=mangrove_evidence_data,
            category="category",
            bar_chart_configs=[
                {
                    "column": "count",
                    "agg_func": "sum",
                    "label": "Count",
                    "text": "count",
                    "textposition": "outside",
                    "textfont_size": 8,
                }
            ],
            layout_kwargs={
                "title": "Mangrove Logging Evidence",
                "title_x": 0.5,
                "title_y": 0.95,
                "font_size": 12,
                "font_color": "black",
                "margin": {"t": 140, "b": 120},
                "yaxis": {"title": "Count", "title_font_size": 10},
                "xaxis": {"title_font_size": 10, "tickangle": 45},
            },
            widget_id="Mangrove Logging Evidence",
            **(params_dict.get("mangrove_evidence_chart") or {}),
        )
        .call()
    )

    persist_mangrove_evidence_html = (
        persist_text.validate()
        .set_task_instance_id("persist_mangrove_evidence_html")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="mangrove_logging_evidence",
            text=mangrove_evidence_chart,
            **(params_dict.get("persist_mangrove_evidence_html") or {}),
        )
        .call()
    )

    png_mangrove_evidence = (
        html_to_png.validate()
        .set_task_instance_id("png_mangrove_evidence")
        .handle_errors()
        .with_tracing()
        .partial(
            html_path=persist_mangrove_evidence_html,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": True,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_mangrove_evidence") or {}),
        )
        .call()
    )

    mangrove_evidence_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("mangrove_evidence_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Mangrove Logging Evidence",
            data=persist_mangrove_evidence_html,
            **(params_dict.get("mangrove_evidence_widget") or {}),
        )
        .call()
    )

    poaching_evidence_data = (
        prepare_category_counts.validate()
        .set_task_instance_id("poaching_evidence_data")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            groupers=groupers,
            count_column="Evidence",
            filter_column="Observation Category 0",
            filter_value="poaching",
            station_column="Station",
            station_filter="Sector",
            exclude_values=None,
            **(params_dict.get("poaching_evidence_data") or {}),
        )
        .call()
    )

    poaching_evidence_chart = (
        draw_bar_chart.validate()
        .set_task_instance_id("poaching_evidence_chart")
        .handle_errors()
        .with_tracing()
        .partial(
            dataframe=poaching_evidence_data,
            category="category",
            bar_chart_configs=[
                {
                    "column": "count",
                    "agg_func": "sum",
                    "label": "Count",
                    "text": "count",
                    "textposition": "outside",
                    "textfont_size": 10,
                }
            ],
            layout_kwargs={
                "title": "Poaching Evidence",
                "title_x": 0.5,
                "title_y": 0.95,
                "font_size": 12,
                "font_color": "black",
                "margin": {"t": 140, "b": 120},
                "yaxis": {"title": "Count", "title_font_size": 10},
                "xaxis": {"title_font_size": 10, "tickangle": 45},
            },
            widget_id="Poaching Evidence",
            **(params_dict.get("poaching_evidence_chart") or {}),
        )
        .call()
    )

    persist_poaching_evidence_html = (
        persist_text.validate()
        .set_task_instance_id("persist_poaching_evidence_html")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="poaching_evidence",
            text=poaching_evidence_chart,
            **(params_dict.get("persist_poaching_evidence_html") or {}),
        )
        .call()
    )

    png_poaching_evidence = (
        html_to_png.validate()
        .set_task_instance_id("png_poaching_evidence")
        .handle_errors()
        .with_tracing()
        .partial(
            html_path=persist_poaching_evidence_html,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_poaching_evidence") or {}),
        )
        .call()
    )

    poaching_evidence_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("poaching_evidence_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Poaching Evidence",
            data=persist_poaching_evidence_html,
            **(params_dict.get("poaching_evidence_widget") or {}),
        )
        .call()
    )

    fishing_gear_data = (
        prepare_category_counts.validate()
        .set_task_instance_id("fishing_gear_data")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            groupers=groupers,
            count_column="Observation",
            filter_column="Resource Use Type",
            filter_value="illegal use",
            exclude_values=["handline", "unknown"],
            station_column="Station",
            station_filter="Sector",
            **(params_dict.get("fishing_gear_data") or {}),
        )
        .call()
    )

    fishing_gear_chart = (
        draw_bar_chart.validate()
        .set_task_instance_id("fishing_gear_chart")
        .handle_errors()
        .with_tracing()
        .partial(
            dataframe=fishing_gear_data,
            category="category",
            bar_chart_configs=[
                {
                    "column": "count",
                    "agg_func": "sum",
                    "label": "Count",
                    "text": "count",
                    "textposition": "outside",
                    "textfont_size": 10,
                }
            ],
            layout_kwargs={
                "title": "Illegal Fishing Gear",
                "title_x": 0.5,
                "title_y": 0.95,
                "font_size": 12,
                "font_color": "black",
                "margin": {"t": 140, "b": 120},
                "yaxis": {"title": "Count", "title_font_size": 10},
                "xaxis": {"title_font_size": 10, "tickangle": 45},
            },
            widget_id="Illegal Fishing Gear",
            **(params_dict.get("fishing_gear_chart") or {}),
        )
        .call()
    )

    persist_fishing_gear_html = (
        persist_text.validate()
        .set_task_instance_id("persist_fishing_gear_html")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="illegal_fishing_gear",
            text=fishing_gear_chart,
            **(params_dict.get("persist_fishing_gear_html") or {}),
        )
        .call()
    )

    html_to_png_fishing_gear_chart = (
        html_to_png.validate()
        .set_task_instance_id("html_to_png_fishing_gear_chart")
        .handle_errors()
        .with_tracing()
        .partial(
            html_path=persist_fishing_gear_html,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("html_to_png_fishing_gear_chart") or {}),
        )
        .call()
    )

    fishing_gear_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("fishing_gear_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Illegal Fishing Gear",
            data=persist_fishing_gear_html,
            **(params_dict.get("fishing_gear_widget") or {}),
        )
        .call()
    )

    illegal_events_by_sector = (
        draw_stacked_bar_chart.validate()
        .set_task_instance_id("illegal_events_by_sector")
        .handle_errors()
        .with_tracing()
        .partial(
            groupers=groupers,
            group_column="Station",
            category_column="Observation Category 0",
            match_values=[
                "mangrove logging",
                "poaching",
                "arrests",
                "poached turtle sum",
            ],
            pivot_on="group",
            date_column=None,
            top_n=None,
            exclude_values=None,
            colors=None,
            remap_column="Resource Use Type",
            remap_value="illegal use",
            remap_label="illegal fishing",
            filter_column="Station",
            filter_value="Sector",
            group_order=[
                "Sector 1",
                "Sector 2",
                "Sector 3",
                "Sector 4",
                "Sector 5",
                "Sector 6",
                "Sector 7",
                "Sector 8",
                "Sector 9",
                "Sector 10",
                "Sector 11",
                "Sector 12",
                "Sector 13",
            ],
            chart_title="Illegal Events by Sector and Activity Type",
            x_axis_label="Sector",
            y_axis_label="Number of Illegal Events",
            widget_id="Illegal Events by Sector",
            **(params_dict.get("illegal_events_by_sector") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_data)
    )

    persist_illegal_sector_html = (
        persist_text.validate()
        .set_task_instance_id("persist_illegal_sector_html")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="illegal_events_by_sector",
            **(params_dict.get("persist_illegal_sector_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=illegal_events_by_sector)
    )

    png_illegal_sector = (
        html_to_png.validate()
        .set_task_instance_id("png_illegal_sector")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_illegal_sector") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_illegal_sector_html)
    )

    illegal_events_sector_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("illegal_events_sector_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Illegal Events by Sector",
            **(params_dict.get("illegal_events_sector_widget") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_illegal_sector_html)
    )

    village_proportional_chart = (
        draw_proportional_bar_chart.validate()
        .set_task_instance_id("village_proportional_chart")
        .handle_errors()
        .with_tracing()
        .partial(
            groupers=groupers,
            group_column="Village",
            metrics=[
                {
                    "label": "Number of Patrols",
                    "column": "Patrol ID",
                    "aggregation": "nunique",
                },
                {
                    "label": "Patrol Hours",
                    "column": "Patrol ID",
                    "aggregation": "nunique",
                },
                {
                    "label": "Total Events",
                    "column": "Observation Category 0",
                    "aggregation": "count",
                },
            ],
            chart_title="Per Village Patrol Proportions",
            widget_id="Village Patrol Proportions",
            filter_column=None,
            filter_value=None,
            colors=None,
            **(params_dict.get("village_proportional_chart") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_data)
    )

    persist_village_prop_html = (
        persist_text.validate()
        .set_task_instance_id("persist_village_prop_html")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="village_proportional",
            **(params_dict.get("persist_village_prop_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=village_proportional_chart)
    )

    html_to_png_village_proportional = (
        html_to_png.validate()
        .set_task_instance_id("html_to_png_village_proportional")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("html_to_png_village_proportional") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_village_prop_html)
    )

    village_proportional_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("village_proportional_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Village Patrol Proportions",
            **(params_dict.get("village_proportional_widget") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_village_prop_html)
    )

    arrests_by_village_data = (
        prepare_grouped_summary.validate()
        .set_task_instance_id("arrests_by_village_data")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data,
            groupers=groupers,
            group_column="Village",
            aggregations={"Arrest_Count": "Observation Category 0:count"},
            most_recent_period_only=False,
            derived_columns=None,
            group_values=None,
            station_column=None,
            station_filter=None,
            **(params_dict.get("arrests_by_village_data") or {}),
        )
        .call()
    )

    arrests_by_village_chart = (
        draw_bar_chart.validate()
        .set_task_instance_id("arrests_by_village_chart")
        .handle_errors()
        .with_tracing()
        .partial(
            dataframe=arrests_by_village_data,
            category="Village",
            bar_chart_configs=[
                {
                    "column": "Arrest_Count",
                    "agg_func": "sum",
                    "label": "Arrests",
                    "text": "Arrest_Count",
                    "textposition": "outside",
                    "textfont_size": 10,
                }
            ],
            layout_kwargs={
                "title": "Number of Arrests by Village",
                "title_x": 0.5,
                "font_size": 12,
                "font_color": "black",
                "yaxis": {"title": "Number of Arrests", "title_font_size": 10},
                "xaxis": {"title": "Village", "title_font_size": 10},
            },
            widget_id="Arrests by Village",
            **(params_dict.get("arrests_by_village_chart") or {}),
        )
        .call()
    )

    persist_arrests_village_html = (
        persist_text.validate()
        .set_task_instance_id("persist_arrests_village_html")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="arrests_by_village",
            text=arrests_by_village_chart,
            **(params_dict.get("persist_arrests_village_html") or {}),
        )
        .call()
    )

    png_arrests_village = (
        html_to_png.validate()
        .set_task_instance_id("png_arrests_village")
        .handle_errors()
        .with_tracing()
        .partial(
            html_path=persist_arrests_village_html,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_arrests_village") or {}),
        )
        .call()
    )

    arrests_village_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("arrests_village_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Arrests by Village",
            data=persist_arrests_village_html,
            **(params_dict.get("arrests_village_widget") or {}),
        )
        .call()
    )

    top_villages_category_chart = (
        draw_stacked_bar_chart.validate()
        .set_task_instance_id("top_villages_category_chart")
        .handle_errors()
        .with_tracing()
        .partial(
            groupers=groupers,
            group_column="Village",
            category_column="Observation Category 0",
            match_values=["mangrove logging", "poaching", "poached turtle"],
            remap_column="Resource Use Type",
            remap_value="illegal use",
            remap_label="illegal fishing",
            top_n=5,
            chart_title="Top 5 Villages: Illegal Activities by Category",
            x_axis_label="Illegal Activity Category",
            y_axis_label="Number of Illegal Events",
            widget_id="Top 5 Villages by Category",
            pivot_on="category",
            date_column=None,
            group_order=None,
            exclude_values=None,
            filter_column=None,
            filter_value=None,
            colors=None,
            **(params_dict.get("top_villages_category_chart") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_data)
    )

    persist_top_villages_cat_html = (
        persist_text.validate()
        .set_task_instance_id("persist_top_villages_cat_html")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="top_villages_by_category",
            **(params_dict.get("persist_top_villages_cat_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=top_villages_category_chart)
    )

    png_top_villages_cat = (
        html_to_png.validate()
        .set_task_instance_id("png_top_villages_cat")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_top_villages_cat") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_top_villages_cat_html)
    )

    top_villages_category_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("top_villages_category_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Top 5 Villages by Category",
            **(params_dict.get("top_villages_category_widget") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_top_villages_cat_html)
    )

    top_villages_monthly_chart = (
        draw_stacked_bar_chart.validate()
        .set_task_instance_id("top_villages_monthly_chart")
        .handle_errors()
        .with_tracing()
        .partial(
            groupers=groupers,
            group_column="Village",
            category_column="Observation Category 0",
            match_values=["mangrove logging", "poaching", "poached turtle"],
            remap_column="Resource Use Type",
            remap_value="illegal use",
            remap_label="illegal fishing",
            top_n=5,
            pivot_on="month",
            date_column="Patrol Start Date",
            chart_title="Top 5 Villages: Illegal Activities Monthly Trend",
            x_axis_label="Month",
            y_axis_label="Number of Illegal Events",
            widget_id="Top 5 Villages Monthly Trend",
            group_order=None,
            exclude_values=None,
            filter_column=None,
            filter_value=None,
            colors=None,
            **(params_dict.get("top_villages_monthly_chart") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_data)
    )

    persist_top_villages_month_html = (
        persist_text.validate()
        .set_task_instance_id("persist_top_villages_month_html")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="top_villages_monthly_trend",
            **(params_dict.get("persist_top_villages_month_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=top_villages_monthly_chart)
    )

    png_top_villages_month = (
        html_to_png.validate()
        .set_task_instance_id("png_top_villages_month")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_top_villages_month") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_top_villages_month_html)
    )

    top_villages_monthly_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("top_villages_monthly_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Top 5 Villages Monthly Trend",
            **(params_dict.get("top_villages_monthly_widget") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_top_villages_month_html)
    )

    village_monthly_timeseries_chart = (
        draw_stacked_bar_chart.validate()
        .set_task_instance_id("village_monthly_timeseries_chart")
        .handle_errors()
        .with_tracing()
        .partial(
            groupers=groupers,
            group_column="Village",
            category_column="Observation Category 0",
            match_values=[
                "mangrove logging",
                "poaching",
                "arrests",
                "poached turtle sum",
            ],
            remap_column="Resource Use Type",
            remap_value="illegal use",
            remap_label="illegal fishing",
            pivot_on="month",
            date_column="Patrol Start Date",
            top_n=5,
            chart_title="Monthly Illegal Activities per Village",
            x_axis_label="Month",
            y_axis_label="Number of Events",
            widget_id="Village Monthly Illegal Activities",
            group_order=None,
            exclude_values=None,
            filter_column=None,
            filter_value=None,
            colors=None,
            **(params_dict.get("village_monthly_timeseries_chart") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_data)
    )

    persist_village_monthly_html = (
        persist_text.validate()
        .set_task_instance_id("persist_village_monthly_html")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="village_monthly_timeseries",
            **(params_dict.get("persist_village_monthly_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=village_monthly_timeseries_chart)
    )

    png_village_month = (
        html_to_png.validate()
        .set_task_instance_id("png_village_month")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 1000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("png_village_month") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_village_monthly_html)
    )

    village_monthly_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("village_monthly_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Village Monthly Illegal Activities",
            **(params_dict.get("village_monthly_widget") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_village_monthly_html)
    )

    illegal_events_map = (
        draw_illegal_events_map.validate()
        .set_task_instance_id("illegal_events_map")
        .handle_errors()
        .with_tracing()
        .partial(
            groupers=groupers,
            marine_layers_path=marine_layers_input,
            widget_id="Illegal Events Map",
            **(params_dict.get("illegal_events_map") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_data)
    )

    persist_illegal_events_html = (
        persist_text.validate()
        .set_task_instance_id("persist_illegal_events_html")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="illegal_events_map",
            **(params_dict.get("persist_illegal_events_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=illegal_events_map)
    )

    html_to_png_illegal_events_map = (
        html_to_png.validate()
        .set_task_instance_id("html_to_png_illegal_events_map")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 60000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("html_to_png_illegal_events_map") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_illegal_events_html)
    )

    illegal_events_map_widget = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("illegal_events_map_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Illegal Events Map",
            **(params_dict.get("illegal_events_map_widget") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_illegal_events_html)
    )

    weighted_effort_map = (
        draw_weighted_effort_map.validate()
        .set_task_instance_id("weighted_effort_map")
        .handle_errors()
        .with_tracing()
        .partial(
            groupers=groupers,
            marine_layers_path=marine_layers_input,
            widget_id="Weighted Patrol Effort Map",
            **(params_dict.get("weighted_effort_map") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_data)
    )

    persist_weighted_effort_html = (
        persist_text.validate()
        .set_task_instance_id("persist_weighted_effort_html")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="weighted_effort_map",
            **(params_dict.get("persist_weighted_effort_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=weighted_effort_map)
    )

    html_to_png_weighted_effort_map = (
        html_to_png.validate()
        .set_task_instance_id("html_to_png_weighted_effort_map")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 60000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("html_to_png_weighted_effort_map") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_weighted_effort_html)
    )

    weighted_effort_map_widget = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("weighted_effort_map_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Weighted Patrol Effort Map",
            **(params_dict.get("weighted_effort_map_widget") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_weighted_effort_html)
    )

    standardized_rate_map = (
        draw_standardized_rate_map.validate()
        .set_task_instance_id("standardized_rate_map")
        .handle_errors()
        .with_tracing()
        .partial(
            groupers=groupers,
            marine_layers_path=marine_layers_input,
            widget_id="Standardised Event Rate Map",
            **(params_dict.get("standardized_rate_map") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_data)
    )

    persist_standardized_rate_html = (
        persist_text.validate()
        .set_task_instance_id("persist_standardized_rate_html")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="standardized_rate_map",
            **(params_dict.get("persist_standardized_rate_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=standardized_rate_map)
    )

    html_to_png_standardized_rate = (
        html_to_png.validate()
        .set_task_instance_id("html_to_png_standardized_rate")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 60000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("html_to_png_standardized_rate") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_standardized_rate_html)
    )

    standardized_rate_map_widget = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("standardized_rate_map_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Standardised Event Rate Map",
            **(params_dict.get("standardized_rate_map_widget") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_standardized_rate_html)
    )

    ecograph_map = (
        draw_ecograph_map.validate()
        .set_task_instance_id("ecograph_map")
        .handle_errors()
        .with_tracing()
        .partial(
            groupers=groupers,
            marine_layers_path=marine_layers_input,
            widget_id="Ecograph Patrol Effort Map",
            **(params_dict.get("ecograph_map") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_data)
    )

    persist_ecograph_html = (
        persist_text.validate()
        .set_task_instance_id("persist_ecograph_html")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="ecograph_map",
            **(params_dict.get("persist_ecograph_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=ecograph_map)
    )

    html_to_png_ecograph_map = (
        html_to_png.validate()
        .set_task_instance_id("html_to_png_ecograph_map")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 60000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("html_to_png_ecograph_map") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_ecograph_html)
    )

    ecograph_map_widget = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("ecograph_map_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Ecograph Patrol Effort Map",
            **(params_dict.get("ecograph_map_widget") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_ecograph_html)
    )

    mangrove_logging_map = (
        draw_mangrove_logging_map.validate()
        .set_task_instance_id("mangrove_logging_map")
        .handle_errors()
        .with_tracing()
        .partial(
            groupers=groupers,
            marine_layers_path=marine_layers_input,
            widget_id="Mangrove Logging Hotspot Map",
            **(params_dict.get("mangrove_logging_map") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_data)
    )

    persist_mangrove_logging_html = (
        persist_text.validate()
        .set_task_instance_id("persist_mangrove_logging_html")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="mangrove_logging_map",
            **(params_dict.get("persist_mangrove_logging_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=mangrove_logging_map)
    )

    html_to_png_mangrove_logging = (
        html_to_png.validate()
        .set_task_instance_id("html_to_png_mangrove_logging")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 60000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("html_to_png_mangrove_logging") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_mangrove_logging_html)
    )

    mangrove_logging_map_widget = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("mangrove_logging_map_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Mangrove Logging Hotspot Map",
            **(params_dict.get("mangrove_logging_map_widget") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_mangrove_logging_html)
    )

    poaching_map = (
        draw_poaching_map.validate()
        .set_task_instance_id("poaching_map")
        .handle_errors()
        .with_tracing()
        .partial(
            groupers=groupers,
            marine_layers_path=marine_layers_input,
            widget_id="Poaching Hotspot Map",
            **(params_dict.get("poaching_map") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_data)
    )

    persist_poaching_html = (
        persist_text.validate()
        .set_task_instance_id("persist_poaching_html")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="poaching_map",
            **(params_dict.get("persist_poaching_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=poaching_map)
    )

    html_to_png_poaching = (
        html_to_png.validate()
        .set_task_instance_id("html_to_png_poaching")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 60000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("html_to_png_poaching") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_poaching_html)
    )

    poaching_map_widget = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("poaching_map_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Poaching Hotspot Map",
            **(params_dict.get("poaching_map_widget") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_poaching_html)
    )

    illegal_fishing_map = (
        draw_illegal_fishing_map.validate()
        .set_task_instance_id("illegal_fishing_map")
        .handle_errors()
        .with_tracing()
        .partial(
            groupers=groupers,
            marine_layers_path=marine_layers_input,
            widget_id="Illegal Fishing Hotspot Map",
            **(params_dict.get("illegal_fishing_map") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_data)
    )

    persist_illegal_fishing_html = (
        persist_text.validate()
        .set_task_instance_id("persist_illegal_fishing_html")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="illegal_fishing_map",
            **(params_dict.get("persist_illegal_fishing_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=illegal_fishing_map)
    )

    html_to_png_illegal_fishing = (
        html_to_png.validate()
        .set_task_instance_id("html_to_png_illegal_fishing")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 60000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("html_to_png_illegal_fishing") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_illegal_fishing_html)
    )

    illegal_fishing_map_widget = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("illegal_fishing_map_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Illegal Fishing Hotspot Map",
            **(params_dict.get("illegal_fishing_map_widget") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_illegal_fishing_html)
    )

    arrests_map = (
        draw_arrests_map.validate()
        .set_task_instance_id("arrests_map")
        .handle_errors()
        .with_tracing()
        .partial(
            groupers=groupers,
            marine_layers_path=marine_layers_input,
            widget_id="Arrests Hotspot Map",
            **(params_dict.get("arrests_map") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_data)
    )

    persist_arrests_html = (
        persist_text.validate()
        .set_task_instance_id("persist_arrests_html")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="arrests_map",
            **(params_dict.get("persist_arrests_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=arrests_map)
    )

    html_to_png_arrests = (
        html_to_png.validate()
        .set_task_instance_id("html_to_png_arrests")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 60000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("html_to_png_arrests") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_arrests_html)
    )

    arrests_map_widget = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("arrests_map_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Arrests Hotspot Map", **(params_dict.get("arrests_map_widget") or {})
        )
        .mapvalues(argnames=["data"], argvalues=persist_arrests_html)
    )

    poached_turtles_map = (
        draw_poached_turtles_map.validate()
        .set_task_instance_id("poached_turtles_map")
        .handle_errors()
        .with_tracing()
        .partial(
            groupers=groupers,
            marine_layers_path=marine_layers_input,
            widget_id="Poached Turtles Hotspot Map",
            **(params_dict.get("poached_turtles_map") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_data)
    )

    persist_poached_turtles_html = (
        persist_text.validate()
        .set_task_instance_id("persist_poached_turtles_html")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="poached_turtles_map",
            **(params_dict.get("persist_poached_turtles_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=poached_turtles_map)
    )

    html_to_png_poached_turtles = (
        html_to_png.validate()
        .set_task_instance_id("html_to_png_poached_turtles")
        .handle_errors()
        .with_tracing()
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 1.0,
                "wait_for_timeout": 60000,
                "timeout": 0,
                "max_concurrent_pages": 1,
            },
            **(params_dict.get("html_to_png_poached_turtles") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=persist_poached_turtles_html)
    )

    poached_turtles_map_widget = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("poached_turtles_map_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            title="Poached Turtles Hotspot Map",
            **(params_dict.get("poached_turtles_map_widget") or {}),
        )
        .mapvalues(argnames=["data"], argvalues=persist_poached_turtles_html)
    )

    report_year = (
        get_report_year.validate()
        .set_task_instance_id("report_year")
        .handle_errors()
        .with_tracing()
        .partial(
            df=clean_data, groupers=groupers, **(params_dict.get("report_year") or {})
        )
        .call()
    )

    report_generation_date = (
        get_generation_date.validate()
        .set_task_instance_id("report_generation_date")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("report_generation_date") or {}))
        .call()
    )

    render_patrol_report = (
        render_report.validate()
        .set_task_instance_id("render_patrol_report")
        .handle_errors()
        .with_tracing()
        .partial(
            template_path=report_template_input,
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            report_year=report_year,
            generation_date=report_generation_date,
            patrol_summary_table=html_to_png_patrol_summary,
            patrol_summary_line=html_to_png_patrols_chart,
            hours_line_chart=html_to_png_hours_chart,
            incidents_line_chart=html_to_png_incidents_chart,
            village_summary_table=html_to_png_village_summary,
            patrol_transport_summary=png_transport_count_chart,
            illegal_activities_summary_dashboard=html_to_png_illegal_activity,
            illegal_activities_doughnut=png_illegal_donut,
            illegal_evidence_text="See charts below for breakdown of illegal activity evidence.",
            mangrove_evidence=png_mangrove_evidence,
            poaching_evidence=png_poaching_evidence,
            illegal_fishing_evidence=html_to_png_fishing_gear_chart,
            village_stacked_bar=png_illegal_sector,
            arrests_by_village_bar=png_arrests_village,
            horizontal_proportional_dashboard=html_to_png_village_proportional,
            all_illegal_hotspot=html_to_png_illegal_events_map,
            mangrove_logging_hotspot=html_to_png_mangrove_logging,
            poaching_hotspot=html_to_png_poaching,
            illegal_fishing_hotspot=html_to_png_illegal_fishing,
            arrests_hotspot=html_to_png_arrests,
            poached_turtles_hotspot=html_to_png_poached_turtles,
            weighted_effort_ecomap=html_to_png_weighted_effort_map,
            standardized_rate_ecomap=html_to_png_standardized_rate,
            ecograph_rate_ecomap=html_to_png_ecograph_map,
            patrol_effort_stacked_bar=png_transport_hours_chart,
            patrol_effort_line=html_to_png_patrol_effort_chart,
            top_villages_by_category=png_top_villages_cat,
            top_villages_monthly_trend=png_top_villages_month,
            violations_over_time_note="Monthly illegal activity charts generated per village for the selected period.",
            **(params_dict.get("render_patrol_report") or {}),
        )
        .call()
    )

    grouped_widgets = (
        groupbykey.validate()
        .set_task_instance_id("grouped_widgets")
        .handle_errors()
        .with_tracing()
        .partial(
            iterables=[
                illegal_activity_donut_widget,
                illegal_events_sector_widget,
                village_proportional_widget,
                top_villages_category_widget,
                top_villages_monthly_widget,
                village_monthly_widget,
                illegal_events_map_widget,
                weighted_effort_map_widget,
                standardized_rate_map_widget,
                ecograph_map_widget,
                mangrove_logging_map_widget,
                poaching_map_widget,
                illegal_fishing_map_widget,
                arrests_map_widget,
                poached_turtles_map_widget,
            ],
            **(params_dict.get("grouped_widgets") or {}),
        )
        .call()
    )

    dashboard_widgets = (
        assemble_dashboard_widgets.validate()
        .set_task_instance_id("dashboard_widgets")
        .handle_errors()
        .with_tracing()
        .partial(
            single_view_widgets=[
                patrol_summary_widget,
                patrols_chart_widget,
                hours_chart_widget,
                incidents_chart_widget,
                village_summary_widget,
                patrol_effort_widget,
                patrol_transport_count_widget,
                patrol_transport_hours_widget,
                illegal_activity_widget,
                mangrove_evidence_widget,
                poaching_evidence_widget,
                fishing_gear_widget,
                arrests_village_widget,
            ],
            keyed_widgets=grouped_widgets,
            **(params_dict.get("dashboard_widgets") or {}),
        )
        .call()
    )

    patrol_summary_dashboard = (
        gather_dashboard.validate()
        .set_task_instance_id("patrol_summary_dashboard")
        .handle_errors()
        .with_tracing()
        .partial(
            widgets=dashboard_widgets,
            details=workflow_details,
            groupers=groupers,
            time_range=time_range,
            **(params_dict.get("patrol_summary_dashboard") or {}),
        )
        .call()
    )

    return patrol_summary_dashboard
